// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 82783e7fcf4f326d "Nexora (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Tablet' | 'Phone' // Variant
}} Props

 */

/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */
import {
	className,
	css,
	fonts,
	stdin_default,
} from "./chunks/chunk-U2NP2CSD.js";
import "./chunks/chunk-Z3H63M2K.js";
import { routes } from "./chunks/chunk-4RDRNIVJ.js";

// virtual:features
import { Fragment as Fragment3 } from "react";
import { ContextProviders } from "unframer";

// /:https://framer.com/m/Features-X8EM.js
import { jsx as _jsx2, jsxs as _jsxs2 } from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	addPropertyControls as addPropertyControls2,
	ComponentViewportProvider,
	ControlType as ControlType2,
	cx as cx2,
	getFonts,
	getFontsFromSharedStyle as getFontsFromSharedStyle2,
	getLoadingLazyAtYPosition as getLoadingLazyAtYPosition2,
	Image as Image2,
	RichText as RichText2,
	SmartComponentScopedContainer,
	useComponentViewport as useComponentViewport2,
	useLocaleInfo as useLocaleInfo2,
	useVariantState as useVariantState2,
	withCSS as withCSS2,
	withFX as withFX2,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React2 from "react";
import { useRef as useRef2 } from "react";

// /:https://framerusercontent.com/modules/qg0plNpELXVUfRdAiw2L/1IE901P7z1eJ2X6RzpNm/WcMloee7m.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";

// /:https://framerusercontent.com/modules/698EdUybpRGsZ5UUDJuM/0q55tx1n5fbVYeREct5y/iBy79QlOk.js
import { fontStore } from "unframer";
fontStore.loadFonts([
	"FS;Satoshi-medium",
	"FS;Satoshi-bold",
	"FS;Satoshi-bold italic",
	"FS;Satoshi-medium italic",
]);
var fonts2 = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "Satoshi",
				source: "fontshare",
				style: "normal",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/P2LQKHE6KA6ZP4AAGN72KDWMHH6ZH3TA/ZC32TK2P7FPS5GFTL46EU6KQJA24ZYDB/7AHDUZ4A7LFLVFUIFSARGIWCRQJHISQP.woff2",
				weight: "500",
			},
			{
				family: "Satoshi",
				source: "fontshare",
				style: "normal",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/LAFFD4SDUCDVQEXFPDC7C53EQ4ZELWQI/PXCT3G6LO6ICM5I3NTYENYPWJAECAWDD/GHM6WVH6MILNYOOCXHXB5GTSGNTMGXZR.woff2",
				weight: "700",
			},
			{
				family: "Satoshi",
				source: "fontshare",
				style: "italic",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/CDEBEFT2R7XKNGXSBBLZGMY4MMHZG75P/HEVKDGQCYDZ7Z6CDVR2ZQGBCTUD6ZARH/BKWEE3VKGTFABE37K2DTH625VUSN2N35.woff2",
				weight: "700",
			},
			{
				family: "Satoshi",
				source: "fontshare",
				style: "italic",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/NID3I7RITWZSKXRCJGOCMP5NOADJK6IG/2HLHGD7OBTWCOHW64YXOE5KFXHU4KJHM/ZHME2QIRFR7UPJ47NLY27RCAFY44CKZJ.woff2",
				weight: "500",
			},
		],
	},
];
var css2 = [
	`.framer-CsBBH .framer-styles-preset-uw75zv:not(.rich-text-wrapper), .framer-CsBBH .framer-styles-preset-uw75zv.rich-text-wrapper p { --framer-font-family: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-bold: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-bold-italic: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-italic: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 24px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 500; --framer-letter-spacing: -0.03em; --framer-line-height: 1.5em; --framer-paragraph-spacing: 20px; --framer-text-alignment: left; --framer-text-color: var(--token-38f68815-7867-4cb4-b7c3-02378b3e2eac, #0d0d0d); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }`,
	`@media (max-width: 1099px) and (min-width: 810px) { .framer-CsBBH .framer-styles-preset-uw75zv:not(.rich-text-wrapper), .framer-CsBBH .framer-styles-preset-uw75zv.rich-text-wrapper p { --framer-font-family: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-bold: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-bold-italic: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-italic: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 23px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: -0.03em; --framer-line-height: 1.5em; --framer-paragraph-spacing: 20px; --framer-text-alignment: left; --framer-text-color: var(--token-38f68815-7867-4cb4-b7c3-02378b3e2eac, #0d0d0d); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }`,
	`@media (max-width: 809px) and (min-width: 0px) { .framer-CsBBH .framer-styles-preset-uw75zv:not(.rich-text-wrapper), .framer-CsBBH .framer-styles-preset-uw75zv.rich-text-wrapper p { --framer-font-family: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-bold: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-bold-italic: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-italic: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 22px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: -0.03em; --framer-line-height: 1.5em; --framer-paragraph-spacing: 20px; --framer-text-alignment: left; --framer-text-color: var(--token-38f68815-7867-4cb4-b7c3-02378b3e2eac, #0d0d0d); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }`,
];
var className2 = "framer-CsBBH";

// /:https://framerusercontent.com/modules/jMdpZHer2aXYKAltt0De/ZDusouqQeIGS6vla3W75/RqWlnUxLg.js
import { fontStore as fontStore2 } from "unframer";
fontStore2.loadFonts([
	"FS;Satoshi-medium",
	"FS;Satoshi-bold",
	"FS;Satoshi-bold italic",
	"FS;Satoshi-medium italic",
]);
var fonts3 = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "Satoshi",
				source: "fontshare",
				style: "normal",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/P2LQKHE6KA6ZP4AAGN72KDWMHH6ZH3TA/ZC32TK2P7FPS5GFTL46EU6KQJA24ZYDB/7AHDUZ4A7LFLVFUIFSARGIWCRQJHISQP.woff2",
				weight: "500",
			},
			{
				family: "Satoshi",
				source: "fontshare",
				style: "normal",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/LAFFD4SDUCDVQEXFPDC7C53EQ4ZELWQI/PXCT3G6LO6ICM5I3NTYENYPWJAECAWDD/GHM6WVH6MILNYOOCXHXB5GTSGNTMGXZR.woff2",
				weight: "700",
			},
			{
				family: "Satoshi",
				source: "fontshare",
				style: "italic",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/CDEBEFT2R7XKNGXSBBLZGMY4MMHZG75P/HEVKDGQCYDZ7Z6CDVR2ZQGBCTUD6ZARH/BKWEE3VKGTFABE37K2DTH625VUSN2N35.woff2",
				weight: "700",
			},
			{
				family: "Satoshi",
				source: "fontshare",
				style: "italic",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/NID3I7RITWZSKXRCJGOCMP5NOADJK6IG/2HLHGD7OBTWCOHW64YXOE5KFXHU4KJHM/ZHME2QIRFR7UPJ47NLY27RCAFY44CKZJ.woff2",
				weight: "500",
			},
		],
	},
];
var css3 = [
	`.framer-PLobl .framer-styles-preset-1ux6xyv:not(.rich-text-wrapper), .framer-PLobl .framer-styles-preset-1ux6xyv.rich-text-wrapper p { --framer-font-family: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-bold: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-bold-italic: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-italic: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 18px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 500; --framer-letter-spacing: -0.02em; --framer-line-height: 1.5em; --framer-paragraph-spacing: 20px; --framer-text-alignment: left; --framer-text-color: var(--token-0e400885-4ad5-460c-800d-ba26ba3d28f7, #636363); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }`,
	`@media (max-width: 1099px) and (min-width: 810px) { .framer-PLobl .framer-styles-preset-1ux6xyv:not(.rich-text-wrapper), .framer-PLobl .framer-styles-preset-1ux6xyv.rich-text-wrapper p { --framer-font-family: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-bold: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-bold-italic: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-italic: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 18px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: -0.02em; --framer-line-height: 1.5em; --framer-paragraph-spacing: 20px; --framer-text-alignment: left; --framer-text-color: var(--token-0e400885-4ad5-460c-800d-ba26ba3d28f7, #636363); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }`,
	`@media (max-width: 809px) and (min-width: 0px) { .framer-PLobl .framer-styles-preset-1ux6xyv:not(.rich-text-wrapper), .framer-PLobl .framer-styles-preset-1ux6xyv.rich-text-wrapper p { --framer-font-family: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-bold: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-bold-italic: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-italic: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 17px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: -0.02em; --framer-line-height: 1.5em; --framer-paragraph-spacing: 20px; --framer-text-alignment: left; --framer-text-color: var(--token-0e400885-4ad5-460c-800d-ba26ba3d28f7, #636363); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }`,
];
var className3 = "framer-PLobl";

// /:https://framerusercontent.com/modules/qg0plNpELXVUfRdAiw2L/1IE901P7z1eJ2X6RzpNm/WcMloee7m.js
var MotionDivWithFX = withFX(motion.div);
var cycleOrder = ["JKmiAhSDA", "w_LyW0cS4"];
var serializationHash = "framer-dri5a";
var variantClassNames = {
	JKmiAhSDA: "framer-v-h25tmc",
	w_LyW0cS4: "framer-v-abyfev",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var animation = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 0.95,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 14,
};
var transition1 = {
	damping: 58,
	delay: 0.1,
	mass: 1,
	stiffness: 425,
	type: "spring",
};
var transition2 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Max Width": "JKmiAhSDA",
	"No Max Width": "w_LyW0cS4",
};
var getProps = ({ heading, height, icon, id, text, width, ...props }) => {
	var _ref, _ref1, _humanReadableVariantMap_props_variant, _ref2, _ref3;
	return {
		...props,
		mlNh9aWrf:
			(_ref = icon !== null && icon !== void 0 ? icon : props.mlNh9aWrf) !==
				null && _ref !== void 0
				? _ref
				: {
						src: "https://framerusercontent.com/images/3vbxHmPnhcGCGq4okmlPGWrIs8.svg",
					},
		nnswguy0W:
			(_ref1 =
				heading !== null && heading !== void 0 ? heading : props.nnswguy0W) !==
				null && _ref1 !== void 0
				? _ref1
				: "Expert Guidance",
		variant:
			(_ref2 =
				(_humanReadableVariantMap_props_variant =
					humanReadableVariantMap[props.variant]) !== null &&
				_humanReadableVariantMap_props_variant !== void 0
					? _humanReadableVariantMap_props_variant
					: props.variant) !== null && _ref2 !== void 0
				? _ref2
				: "JKmiAhSDA",
		XD7Kre3t6:
			(_ref3 = text !== null && text !== void 0 ? text : props.XD7Kre3t6) !==
				null && _ref3 !== void 0
				? _ref3
				: "Receive professional insights to make informed estate.",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		mlNh9aWrf,
		nnswguy0W,
		XD7Kre3t6,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "JKmiAhSDA",
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [className2, className3];
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants animate={variants} initial={false}>
				<Transition value={transition2}>
					<MotionDivWithFX
						{...restProps}
						{...gestureHandlers}
						__framer__animate={{
							transition: transition1,
						}}
						__framer__animateOnce={true}
						__framer__enter={animation}
						__framer__styleAppearEffectEnabled={true}
						__framer__threshold={0.5}
						__perspectiveFX={false}
						__smartComponentFX={true}
						__targetOpacity={1}
						className={cx(
							serializationHash,
							...sharedStyleClassNames,
							"framer-h25tmc",
							className4,
							classNames,
						)}
						data-framer-name={"Max Width"}
						layoutDependency={layoutDependency}
						layoutId={"JKmiAhSDA"}
						ref={ref !== null && ref !== void 0 ? ref : ref1}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								w_LyW0cS4: {
									"data-framer-name": "No Max Width",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-1jdzcvw"}
							data-framer-name={"Icon-wrapper"}
							layoutDependency={layoutDependency}
							layoutId={"ufEIQZmtW"}
							style={{
								backgroundColor:
									"var(--token-37c73a71-ed98-4730-86d9-6e0a52d466b3, rgb(46, 105, 255))",
								borderBottomLeftRadius: 16,
								borderBottomRightRadius: 16,
								borderTopLeftRadius: 16,
								borderTopRightRadius: 16,
							}}
						>
							<Image
								background={{
									alt: "",
									fit: "fit",
									loading: getLoadingLazyAtYPosition(
										((componentViewport === null || componentViewport === void 0
											? void 0
											: componentViewport.y) || 0) +
											0 +
											0 +
											12,
									),
									pixelHeight: 800,
									pixelWidth: 800,
									sizes: "30px",
									...toResponsiveImage(mlNh9aWrf),
									...{
										positionX: "center",
										positionY: "center",
									},
								}}
								className={"framer-16qa6pc"}
								data-framer-name={"Icon"}
								layoutDependency={layoutDependency}
								layoutId={"oySAw5hF4"}
							/>
						</motion.div>
						<motion.div
							className={"framer-18k3zhy"}
							data-framer-name={"Text-wrapper"}
							layoutDependency={layoutDependency}
							layoutId={"FpBh7ghmz"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-1kzasy6"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"pegO_4L6i"}
								style={{
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={nnswguy0W}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-uw75zv"}
										data-styles-preset={"iBy79QlOk"}
									>
										{"Expert Guidance"}
									</motion.p>
								</React.Fragment>
							</RichText>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-mnjeeu"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"Oq57FxcG0"}
								style={{
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={XD7Kre3t6}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-1ux6xyv"}
										data-styles-preset={"RqWlnUxLg"}
									>
										{"Receive professional insights to make informed estate."}
									</motion.p>
								</React.Fragment>
							</RichText>
						</motion.div>
					</MotionDivWithFX>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-dri5a.framer-xgndnq, .framer-dri5a .framer-xgndnq { display: block; }",
	".framer-dri5a.framer-h25tmc { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px 0px 18px 0px; position: relative; width: 349px; }",
	".framer-dri5a .framer-1jdzcvw { align-content: center; align-items: center; aspect-ratio: 1 / 1; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: var(--framer-aspect-ratio-supported, 54px); justify-content: center; overflow: visible; padding: 0px; position: relative; width: 54px; }",
	".framer-dri5a .framer-16qa6pc { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 30px); overflow: hidden; position: relative; width: 30px; }",
	".framer-dri5a .framer-18k3zhy { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-dri5a .framer-1kzasy6 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-dri5a .framer-mnjeeu { flex: none; height: auto; max-width: 260px; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-dri5a.framer-h25tmc, .framer-dri5a .framer-1jdzcvw, .framer-dri5a .framer-18k3zhy { gap: 0px; } .framer-dri5a.framer-h25tmc > * { margin: 0px; margin-bottom: calc(24px / 2); margin-top: calc(24px / 2); } .framer-dri5a.framer-h25tmc > :first-child, .framer-dri5a .framer-18k3zhy > :first-child { margin-top: 0px; } .framer-dri5a.framer-h25tmc > :last-child, .framer-dri5a .framer-18k3zhy > :last-child { margin-bottom: 0px; } .framer-dri5a .framer-1jdzcvw > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-dri5a .framer-1jdzcvw > :first-child { margin-left: 0px; } .framer-dri5a .framer-1jdzcvw > :last-child { margin-right: 0px; } .framer-dri5a .framer-18k3zhy > * { margin: 0px; margin-bottom: calc(8px / 2); margin-top: calc(8px / 2); } }",
	".framer-dri5a.framer-v-abyfev .framer-mnjeeu { max-width: 95%; }",
	...css2,
	...css3,
];
var FramerWcMloee7m = withCSS(Component, css4, "framer-dri5a");
var stdin_default2 = FramerWcMloee7m;
FramerWcMloee7m.displayName = "Feature Item";
FramerWcMloee7m.defaultProps = {
	height: 194,
	width: 349,
};
addPropertyControls(FramerWcMloee7m, {
	variant: {
		options: ["JKmiAhSDA", "w_LyW0cS4"],
		optionTitles: ["Max Width", "No Max Width"],
		title: "Variant",
		type: ControlType.Enum,
	},
	mlNh9aWrf: {
		__defaultAssetReference:
			"data:framer/asset-reference,3vbxHmPnhcGCGq4okmlPGWrIs8.svg?originalFilename=documents-svgrepo-com+%281%29.svg&preferredSize=auto",
		title: "Icon",
		type: ControlType.ResponsiveImage,
	},
	nnswguy0W: {
		defaultValue: "Expert Guidance",
		displayTextArea: false,
		title: "Heading",
		type: ControlType.String,
	},
	XD7Kre3t6: {
		defaultValue: "Receive professional insights to make informed estate.",
		displayTextArea: true,
		title: "Text",
		type: ControlType.String,
	},
});
addFonts(
	FramerWcMloee7m,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts3),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framer.com/m/Features-X8EM.js
var SectionTagFonts = getFonts(stdin_default);
var FeatureItemFonts = getFonts(stdin_default2);
var ImageWithFX = withFX2(Image2);
var cycleOrder2 = ["CkK__cZph", "s0nKrx2p9", "OryBcOlS4"];
var serializationHash2 = "framer-BltYr";
var variantClassNames2 = {
	CkK__cZph: "framer-v-1uhv8k2",
	OryBcOlS4: "framer-v-1p4892h",
	s0nKrx2p9: "framer-v-1p7u1n5",
};
function addPropertyOverrides2(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition12 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var addImageAlt = (image, alt) => {
	if (!image || typeof image !== "object") {
		return;
	}
	return {
		...image,
		alt,
	};
};
var animation2 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 0.85,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 30,
};
var transition22 = {
	damping: 54,
	delay: 0,
	mass: 1,
	stiffness: 400,
	type: "spring",
};
var Transition2 = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext2);
	const transition = value ?? config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider value={contextValue}>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var Variants2 = motion2.create(React2.Fragment);
var humanReadableVariantMap2 = {
	Desktop: "CkK__cZph",
	Phone: "OryBcOlS4",
	Tablet: "s0nKrx2p9",
};
var getProps2 = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap2[props.variant] ?? props.variant ?? "CkK__cZph",
	};
};
var createLayoutDependency2 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React2.useId();
	const { activeLocale, setLocale } = useLocaleInfo2();
	const componentViewport = useComponentViewport2();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		cycleOrder: cycleOrder2,
		defaultVariant: "CkK__cZph",
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx2(serializationHash2, ...sharedStyleClassNames);
	return (
		<LayoutGroup2 id={layoutId ?? defaultLayoutId}>
			<Variants2 animate={variants} initial={false}>
				<Transition2 value={transition12}>
					<motion2.section
						{...restProps}
						{...gestureHandlers}
						className={cx2(
							scopingClassNames,
							"framer-1uhv8k2",
							className4,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"CkK__cZph"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides2(
							{
								OryBcOlS4: {
									"data-framer-name": "Phone",
								},
								s0nKrx2p9: {
									"data-framer-name": "Tablet",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion2.div
							className={"framer-1krld8y"}
							data-framer-name={"Container"}
							layoutDependency={layoutDependency}
							layoutId={"ucXZD8GG7"}
						>
							<motion2.div
								className={"framer-l846ol"}
								data-framer-name={"Heading-Wrapper"}
								layoutDependency={layoutDependency}
								layoutId={"FmptG7xJj"}
							>
								<ComponentViewportProvider
									height={35}
									y={
										(componentViewport?.y || 0) +
										(68 +
											((componentViewport?.height || 933) - 136 - 737) / 2) +
										0 +
										0 +
										0 +
										0
									}
									{...addPropertyOverrides2(
										{
											OryBcOlS4: {
												y:
													(componentViewport?.y || 0) +
													58 +
													(((componentViewport?.height || 1799) - 116 - 1503) /
														2 +
														0 +
														0) +
													0 +
													0 +
													0 +
													0,
											},
											s0nKrx2p9: {
												y:
													(componentViewport?.y || 0) +
													(58 +
														((componentViewport?.height || 1385) - 116 - 1209) /
															2) +
													0 +
													0 +
													0 +
													0,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainer
										className={"framer-9wwbp0-container"}
										data-framer-name={"Section-Tag"}
										layoutDependency={layoutDependency}
										layoutId={"mb3b9hLzi-container"}
										name={"Section-Tag"}
										nodeId={"mb3b9hLzi"}
										rendersWithMotion={true}
										scopeId={"jGJp5WdJX"}
									>
										{_jsx2(stdin_default, {
											height: "100%",
											id: "mb3b9hLzi",
											layoutId: "mb3b9hLzi",
											name: "Section-Tag",
											OaXHVEg_A: "Features",
											variant: "iPSP_xFIy",
											width: "100%",
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
								<RichText2
									__fromCanvasComponent={true}
									className={"framer-15kgndo"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"wxTw7R87y"}
									style={{
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React2.Fragment>
										<motion2.h2
											className={"framer-styles-preset-jaa7lk"}
											data-styles-preset={"u1TMq5IXn"}
											style={{
												"--framer-text-alignment": "center",
											}}
										>
											{"Expertise you can count on to achieve your most"}
										</motion2.h2>
									</React2.Fragment>
								</RichText2>
							</motion2.div>
							<motion2.div
								className={"framer-1mf87h2"}
								data-framer-name={"Main-wrapper"}
								layoutDependency={layoutDependency}
								layoutId={"G6H2v4l6U"}
							>
								<motion2.div
									className={"framer-s2r28e"}
									data-framer-name={"Grid-2x"}
									layoutDependency={layoutDependency}
									layoutId={"GwPLqwKKU"}
								>
									<ComponentViewportProvider
										height={194}
										width={`max((max((min(max(${componentViewport?.width || "100vw"}, 1px), 1200px) - 50px) / 2, 50px) - 36px) / 2, 50px)`}
										y={
											(componentViewport?.y || 0) +
											(68 +
												((componentViewport?.height || 933) - 136 - 737) / 2) +
											0 +
											207 +
											0 +
											0 +
											25 +
											0
										}
										{...addPropertyOverrides2(
											{
												OryBcOlS4: {
													width: `max(min(${componentViewport?.width || "100vw"}, 1200px) - 40px, 50px)`,
													y:
														(componentViewport?.y || 0) +
														58 +
														(((componentViewport?.height || 1799) -
															116 -
															1503) /
															2 +
															0 +
															0) +
														0 +
														181 +
														0 +
														0 +
														0 +
														0,
												},
												s0nKrx2p9: {
													width: `max((max(min(max(${componentViewport?.width || "100vw"}, 1px), 1200px) - 50px, 50px) - 36px) / 2, 50px)`,
													y:
														(componentViewport?.y || 0) +
														(58 +
															((componentViewport?.height || 1385) -
																116 -
																1209) /
																2) +
														0 +
														207 +
														0 +
														578 +
														0 +
														0,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<SmartComponentScopedContainer
											className={"framer-1yg5hxd-container"}
											data-framer-name={"Features"}
											layoutDependency={layoutDependency}
											layoutId={"LmbOmUcKP-container"}
											name={"Features"}
											nodeId={"LmbOmUcKP"}
											rendersWithMotion={true}
											scopeId={"jGJp5WdJX"}
										>
											{_jsx2(stdin_default2, {
												height: "100%",
												id: "LmbOmUcKP",
												layoutId: "LmbOmUcKP",
												mlNh9aWrf: addImageAlt(
													{
														pixelHeight: 24,
														pixelWidth: 24,
														src: "https://framerusercontent.com/images/1EdiAQPtZngDAXZvIBVt6YZQMOs.svg",
													},
													"",
												),
												name: "Features",
												nnswguy0W: "Tailored Strategies",
												style: {
													width: "100%",
												},
												variant: "JKmiAhSDA",
												width: "100%",
												XD7Kre3t6:
													"Get customized plans designed to align with your unique business goals.",
												...addPropertyOverrides2(
													{
														OryBcOlS4: {
															variant: "w_LyW0cS4",
														},
														s0nKrx2p9: {
															variant: "w_LyW0cS4",
														},
													},
													baseVariant,
													gestureVariant,
												),
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
									<ComponentViewportProvider
										height={194}
										width={`max((max((min(max(${componentViewport?.width || "100vw"}, 1px), 1200px) - 50px) / 2, 50px) - 36px) / 2, 50px)`}
										y={
											(componentViewport?.y || 0) +
											(68 +
												((componentViewport?.height || 933) - 136 - 737) / 2) +
											0 +
											207 +
											0 +
											0 +
											25 +
											0
										}
										{...addPropertyOverrides2(
											{
												OryBcOlS4: {
													width: `max(min(${componentViewport?.width || "100vw"}, 1200px) - 40px, 50px)`,
													y:
														(componentViewport?.y || 0) +
														58 +
														(((componentViewport?.height || 1799) -
															116 -
															1503) /
															2 +
															0 +
															0) +
														0 +
														181 +
														0 +
														0 +
														0 +
														230,
												},
												s0nKrx2p9: {
													width: `max((max(min(max(${componentViewport?.width || "100vw"}, 1px), 1200px) - 50px, 50px) - 36px) / 2, 50px)`,
													y:
														(componentViewport?.y || 0) +
														(58 +
															((componentViewport?.height || 1385) -
																116 -
																1209) /
																2) +
														0 +
														207 +
														0 +
														578 +
														0 +
														0,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<SmartComponentScopedContainer
											className={"framer-1ieh084-container"}
											data-framer-name={"Features"}
											layoutDependency={layoutDependency}
											layoutId={"OyekVF_Pa-container"}
											name={"Features"}
											nodeId={"OyekVF_Pa"}
											rendersWithMotion={true}
											scopeId={"jGJp5WdJX"}
										>
											{_jsx2(stdin_default2, {
												height: "100%",
												id: "OyekVF_Pa",
												layoutId: "OyekVF_Pa",
												mlNh9aWrf: addImageAlt(
													{
														pixelHeight: 25,
														pixelWidth: 25,
														src: "https://framerusercontent.com/images/nK5FIrBu2W1QnWt7F7A76OOkNzs.svg",
													},
													"",
												),
												name: "Features",
												nnswguy0W: "Expert Analysis",
												style: {
													width: "100%",
												},
												variant: "JKmiAhSDA",
												width: "100%",
												XD7Kre3t6:
													"Leverage data-driven insights to make smarter decisions and stay ahead.",
												...addPropertyOverrides2(
													{
														OryBcOlS4: {
															variant: "w_LyW0cS4",
														},
														s0nKrx2p9: {
															variant: "w_LyW0cS4",
														},
													},
													baseVariant,
													gestureVariant,
												),
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
									<ComponentViewportProvider
										height={194}
										width={`max((max((min(max(${componentViewport?.width || "100vw"}, 1px), 1200px) - 50px) / 2, 50px) - 36px) / 2, 50px)`}
										y={
											(componentViewport?.y || 0) +
											(68 +
												((componentViewport?.height || 933) - 136 - 737) / 2) +
											0 +
											207 +
											0 +
											0 +
											25 +
											230
										}
										{...addPropertyOverrides2(
											{
												OryBcOlS4: {
													width: `max(min(${componentViewport?.width || "100vw"}, 1200px) - 40px, 50px)`,
													y:
														(componentViewport?.y || 0) +
														58 +
														(((componentViewport?.height || 1799) -
															116 -
															1503) /
															2 +
															0 +
															0) +
														0 +
														181 +
														0 +
														0 +
														0 +
														460,
												},
												s0nKrx2p9: {
													width: `max((max(min(max(${componentViewport?.width || "100vw"}, 1px), 1200px) - 50px, 50px) - 36px) / 2, 50px)`,
													y:
														(componentViewport?.y || 0) +
														(58 +
															((componentViewport?.height || 1385) -
																116 -
																1209) /
																2) +
														0 +
														207 +
														0 +
														578 +
														0 +
														230,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<SmartComponentScopedContainer
											className={"framer-6mded1-container"}
											data-framer-name={"Features"}
											layoutDependency={layoutDependency}
											layoutId={"sCk99PAAU-container"}
											name={"Features"}
											nodeId={"sCk99PAAU"}
											rendersWithMotion={true}
											scopeId={"jGJp5WdJX"}
										>
											{_jsx2(stdin_default2, {
												height: "100%",
												id: "sCk99PAAU",
												layoutId: "sCk99PAAU",
												mlNh9aWrf: addImageAlt(
													{
														pixelHeight: 24,
														pixelWidth: 24,
														src: "https://framerusercontent.com/images/qZeNjj6DIXgksqzzaIH2krvnvQ.svg",
													},
													"",
												),
												name: "Features",
												nnswguy0W: "Seamless Collaboration",
												style: {
													width: "100%",
												},
												variant: "JKmiAhSDA",
												width: "100%",
												XD7Kre3t6:
													"Work closely with our team for a hands-on, personalized consulting experience.",
												...addPropertyOverrides2(
													{
														OryBcOlS4: {
															variant: "w_LyW0cS4",
														},
														s0nKrx2p9: {
															variant: "w_LyW0cS4",
														},
													},
													baseVariant,
													gestureVariant,
												),
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
									<ComponentViewportProvider
										height={194}
										width={`max((max((min(max(${componentViewport?.width || "100vw"}, 1px), 1200px) - 50px) / 2, 50px) - 36px) / 2, 50px)`}
										y={
											(componentViewport?.y || 0) +
											(68 +
												((componentViewport?.height || 933) - 136 - 737) / 2) +
											0 +
											207 +
											0 +
											0 +
											25 +
											230
										}
										{...addPropertyOverrides2(
											{
												OryBcOlS4: {
													width: `max(min(${componentViewport?.width || "100vw"}, 1200px) - 40px, 50px)`,
													y:
														(componentViewport?.y || 0) +
														58 +
														(((componentViewport?.height || 1799) -
															116 -
															1503) /
															2 +
															0 +
															0) +
														0 +
														181 +
														0 +
														0 +
														0 +
														690,
												},
												s0nKrx2p9: {
													width: `max((max(min(max(${componentViewport?.width || "100vw"}, 1px), 1200px) - 50px, 50px) - 36px) / 2, 50px)`,
													y:
														(componentViewport?.y || 0) +
														(58 +
															((componentViewport?.height || 1385) -
																116 -
																1209) /
																2) +
														0 +
														207 +
														0 +
														578 +
														0 +
														230,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<SmartComponentScopedContainer
											className={"framer-1wj8bnn-container"}
											data-framer-name={"Features"}
											layoutDependency={layoutDependency}
											layoutId={"KQnYSkNKj-container"}
											name={"Features"}
											nodeId={"KQnYSkNKj"}
											rendersWithMotion={true}
											scopeId={"jGJp5WdJX"}
										>
											{_jsx2(stdin_default2, {
												height: "100%",
												id: "KQnYSkNKj",
												layoutId: "KQnYSkNKj",
												mlNh9aWrf: addImageAlt(
													{
														pixelHeight: 24,
														pixelWidth: 24,
														src: "https://framerusercontent.com/images/aNNNqLdNJfCiU3NT8EjGuPlt2GY.svg",
													},
													"",
												),
												name: "Features",
												nnswguy0W: "Actionable Solutions",
												style: {
													width: "100%",
												},
												variant: "JKmiAhSDA",
												width: "100%",
												XD7Kre3t6:
													"Implement practical strategies that deliver measurable and lasting results.",
												...addPropertyOverrides2(
													{
														OryBcOlS4: {
															variant: "w_LyW0cS4",
														},
														s0nKrx2p9: {
															variant: "w_LyW0cS4",
														},
													},
													baseVariant,
													gestureVariant,
												),
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								</motion2.div>
								<motion2.div
									className={"framer-1kizu6q"}
									data-framer-name={"Image-wrapper"}
									layoutDependency={layoutDependency}
									layoutId={"fbmcbrPFX"}
								>
									<ImageWithFX
										__framer__animate={{
											transition: transition22,
										}}
										__framer__animateOnce={true}
										__framer__enter={animation2}
										__framer__styleAppearEffectEnabled={true}
										__framer__threshold={0.5}
										__perspectiveFX={false}
										__smartComponentFX={true}
										__targetOpacity={1}
										background={{
											alt: "",
											fit: "fill",
											loading: getLoadingLazyAtYPosition2(
												(componentViewport?.y || 0) +
													(68 +
														((componentViewport?.height || 933) - 136 - 737) /
															2) +
													0 +
													207 +
													0 +
													0 +
													0,
											),
											pixelHeight: 900,
											pixelWidth: 900,
											sizes: `min(max(max((min(max(${componentViewport?.width || "100vw"}, 1px), 1200px) - 50px) / 2, 50px) - 48px, 1px), 475px)`,
											src: "https://framerusercontent.com/images/t8x0xmyfmoHo5oT8OnkS78SIus.jpg",
											srcSet:
												"https://framerusercontent.com/images/t8x0xmyfmoHo5oT8OnkS78SIus.jpg?scale-down-to=512 512w,https://framerusercontent.com/images/t8x0xmyfmoHo5oT8OnkS78SIus.jpg 900w",
										}}
										className={"framer-cs4tfk"}
										data-framer-name={"Image"}
										layoutDependency={layoutDependency}
										layoutId={"RLWUq_301"}
										style={{
											borderBottomLeftRadius: 28,
											borderBottomRightRadius: 28,
											borderTopLeftRadius: 28,
											borderTopRightRadius: 28,
										}}
										{...addPropertyOverrides2(
											{
												OryBcOlS4: {
													background: {
														alt: "",
														fit: "fill",
														loading: getLoadingLazyAtYPosition2(
															(componentViewport?.y || 0) +
																58 +
																(((componentViewport?.height || 1799) -
																	116 -
																	1503) /
																	2 +
																	0 +
																	0) +
																0 +
																181 +
																0 +
																922 +
																0,
														),
														pixelHeight: 900,
														pixelWidth: 900,
														sizes: `max(max(min(${componentViewport?.width || "100vw"}, 1200px) - 40px, 50px), 1px)`,
														src: "https://framerusercontent.com/images/t8x0xmyfmoHo5oT8OnkS78SIus.jpg",
														srcSet:
															"https://framerusercontent.com/images/t8x0xmyfmoHo5oT8OnkS78SIus.jpg?scale-down-to=512 512w,https://framerusercontent.com/images/t8x0xmyfmoHo5oT8OnkS78SIus.jpg 900w",
													},
												},
												s0nKrx2p9: {
													background: {
														alt: "",
														fit: "fill",
														loading: getLoadingLazyAtYPosition2(
															(componentViewport?.y || 0) +
																(58 +
																	((componentViewport?.height || 1385) -
																		116 -
																		1209) /
																		2) +
																0 +
																207 +
																0 +
																0 +
																0,
														),
														pixelHeight: 900,
														pixelWidth: 900,
														sizes: `max(max(min(max(${componentViewport?.width || "100vw"}, 1px), 1200px) - 50px, 50px), 1px)`,
														src: "https://framerusercontent.com/images/t8x0xmyfmoHo5oT8OnkS78SIus.jpg",
														srcSet:
															"https://framerusercontent.com/images/t8x0xmyfmoHo5oT8OnkS78SIus.jpg?scale-down-to=512 512w,https://framerusercontent.com/images/t8x0xmyfmoHo5oT8OnkS78SIus.jpg 900w",
													},
												},
											},
											baseVariant,
											gestureVariant,
										)}
									/>
								</motion2.div>
							</motion2.div>
						</motion2.div>
					</motion2.section>
				</Transition2>
			</Variants2>
		</LayoutGroup2>
	);
});
var css5 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-BltYr.framer-de9xgf, .framer-BltYr .framer-de9xgf { display: block; }",
	".framer-BltYr.framer-1uhv8k2 { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 68px 0px 68px 0px; position: relative; width: 1200px; }",
	".framer-BltYr .framer-1krld8y { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 88px; height: min-content; justify-content: flex-end; max-width: 1200px; overflow: visible; padding: 0px 25px 0px 25px; position: relative; width: 1px; }",
	".framer-BltYr .framer-l846ol { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-BltYr .framer-9wwbp0-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-BltYr .framer-15kgndo { flex: none; height: auto; max-width: 645px; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-BltYr .framer-1mf87h2 { display: grid; flex: none; gap: 0px; grid-auto-rows: min-content; grid-template-columns: repeat(2, minmax(50px, 1fr)); grid-template-rows: repeat(1, min-content); height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-BltYr .framer-s2r28e { align-self: start; display: grid; flex: none; gap: 36px; grid-auto-rows: min-content; grid-template-columns: repeat(2, minmax(50px, 1fr)); grid-template-rows: repeat(1, min-content); height: auto; justify-content: center; justify-self: start; overflow: hidden; padding: 25px 0px 25px 0px; position: relative; width: 100%; }",
	".framer-BltYr .framer-1yg5hxd-container, .framer-BltYr .framer-1ieh084-container, .framer-BltYr .framer-6mded1-container, .framer-BltYr .framer-1wj8bnn-container { align-self: start; flex: none; height: auto; justify-self: start; position: relative; width: 100%; }",
	".framer-BltYr .framer-1kizu6q { align-content: center; align-items: center; align-self: start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-end; justify-self: start; overflow: hidden; padding: 0px 0px 0px 48px; position: relative; width: 100%; }",
	".framer-BltYr .framer-cs4tfk { aspect-ratio: 0.8962264150943396 / 1; flex: 1 0 0px; height: var(--framer-aspect-ratio-supported, 530px); max-width: 475px; overflow: hidden; position: relative; width: 1px; will-change: var(--framer-will-change-override, transform); }",
	".framer-BltYr.framer-v-1p7u1n5.framer-1uhv8k2 { padding: 58px 0px 58px 0px; width: 810px; }",
	".framer-BltYr.framer-v-1p7u1n5 .framer-1mf87h2 { gap: 48px; grid-template-columns: repeat(1, minmax(50px, 1fr)); }",
	".framer-BltYr.framer-v-1p7u1n5 .framer-s2r28e { order: 1; padding: 0px; }",
	".framer-BltYr.framer-v-1p7u1n5 .framer-1kizu6q { order: 0; padding: 0px; }",
	".framer-BltYr.framer-v-1p7u1n5 .framer-cs4tfk { aspect-ratio: unset; height: 530px; max-width: unset; }",
	".framer-BltYr.framer-v-1p4892h.framer-1uhv8k2 { flex-direction: column; padding: 58px 0px 58px 0px; width: 390px; }",
	".framer-BltYr.framer-v-1p4892h .framer-1krld8y { flex: none; gap: 62px; padding: 0px 20px 0px 20px; width: 100%; }",
	".framer-BltYr.framer-v-1p4892h .framer-1mf87h2 { gap: 38px; grid-template-columns: repeat(1, minmax(50px, 1fr)); }",
	".framer-BltYr.framer-v-1p4892h .framer-s2r28e { grid-template-columns: repeat(1, minmax(50px, 1fr)); padding: 0px; }",
	".framer-BltYr.framer-v-1p4892h .framer-1kizu6q { padding: 0px; }",
	".framer-BltYr.framer-v-1p4892h .framer-cs4tfk { aspect-ratio: unset; height: 400px; max-width: unset; }",
	...css,
];
var FramerjGJp5WdJX = withCSS2(Component2, css5, "framer-BltYr");
var stdin_default3 = FramerjGJp5WdJX;
FramerjGJp5WdJX.displayName = "Features";
FramerjGJp5WdJX.defaultProps = {
	height: 933,
	width: 1200,
};
addPropertyControls2(FramerjGJp5WdJX, {
	variant: {
		options: ["CkK__cZph", "s0nKrx2p9", "OryBcOlS4"],
		optionTitles: ["Desktop", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType2.Enum,
	},
});
addFonts2(
	FramerjGJp5WdJX,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...SectionTagFonts,
		...FeatureItemFonts,
		...getFontsFromSharedStyle2(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:features
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "OryBcOlS4",
	md: "s0nKrx2p9",
	xl: "CkK__cZph",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"82783e7fcf4f326d8d9b4a72041dedf3d5360c1cd183094c631a3a227d30a683"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default3, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * Renders FeaturesFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale, ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"82783e7fcf4f326d8d9b4a72041dedf3d5360c1cd183094c631a3a227d30a683"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default3}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default3);
var features_default = ComponentWithRoot;
export { features_default as default };
