// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 82783e7fcf4f326d "Nexora (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Tablet' | 'Phone' // Variant
}} Props

 */

/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */
import { className, css, fonts } from "./chunks/chunk-Z3H63M2K.js";
import { routes } from "./chunks/chunk-4RDRNIVJ.js";

// virtual:header
import { Fragment as Fragment6 } from "react";
import { ContextProviders } from "unframer";

// /:https://framer.com/m/HEADER-fAug.js
import { jsx as _jsx5 } from "react/jsx-runtime";
import {
	addFonts as addFonts5,
	addPropertyControls as addPropertyControls3,
	ComponentViewportProvider as ComponentViewportProvider2,
	ControlType as ControlType3,
	cx as cx5,
	getFonts as getFonts2,
	SmartComponentScopedContainer as SmartComponentScopedContainer2,
	useComponentViewport as useComponentViewport5,
	useLocaleInfo as useLocaleInfo5,
	useVariantState as useVariantState5,
	withCSS as withCSS5,
} from "unframer";
import {
	LayoutGroup as LayoutGroup5,
	motion as motion5,
	MotionConfigContext as MotionConfigContext5,
} from "unframer";
import * as React5 from "react";
import { useRef as useRef5 } from "react";

// /:https://framerusercontent.com/modules/1aSY1Lif3VzM4GvYmEkn/OetkHbKoEQPl2GP1n1sW/tnMZEkN8f.js
import { jsx as _jsx4, jsxs as _jsxs4 } from "react/jsx-runtime";
import {
	addFonts as addFonts4,
	ComponentViewportProvider,
	cx as cx4,
	getFonts,
	getFontsFromSharedStyle as getFontsFromSharedStyle4,
	Image as Image3,
	ResolveLinks,
	RichText as RichText4,
	SmartComponentScopedContainer,
	useComponentViewport as useComponentViewport4,
	useLocaleInfo as useLocaleInfo4,
	useRouter,
	useVariantState as useVariantState4,
	withCSS as withCSS4,
	withFX,
	withOptimizedAppearEffect,
} from "unframer";
import {
	LayoutGroup as LayoutGroup4,
	motion as motion4,
	MotionConfigContext as MotionConfigContext4,
} from "unframer";
import * as React4 from "react";
import { useRef as useRef4 } from "react";

// /:https://framerusercontent.com/modules/iWet5NirrpSptCdRlqaU/SxTGAjKgJUQ6TdJeEhQG/IBuebZNpT.js
import { fontStore } from "unframer";
fontStore.loadFonts([
	"GF;Instrument Sans-500",
	"GF;Instrument Sans-700",
	"GF;Instrument Sans-700italic",
	"GF;Instrument Sans-500italic",
]);
var fonts2 = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "Instrument Sans",
				source: "google",
				style: "normal",
				url: "https://fonts.gstatic.com/s/instrumentsans/v1/pximypc9vsFDm051Uf6KVwgkfoSxQ0GsQv8ToedPibnr-yp2JGEJOH9npST3-QfwmS0v3_7Y.woff2",
				weight: "500",
			},
			{
				family: "Instrument Sans",
				source: "google",
				style: "normal",
				url: "https://fonts.gstatic.com/s/instrumentsans/v1/pximypc9vsFDm051Uf6KVwgkfoSxQ0GsQv8ToedPibnr-yp2JGEJOH9npSQi_gfwmS0v3_7Y.woff2",
				weight: "700",
			},
			{
				family: "Instrument Sans",
				source: "google",
				style: "italic",
				url: "https://fonts.gstatic.com/s/instrumentsans/v1/pxigypc9vsFDm051Uf6KVwgkfoSbSnNPooZAN0lInHGpCWNE27lgU-XJojENugixkywN2u7YUwU.woff2",
				weight: "700",
			},
			{
				family: "Instrument Sans",
				source: "google",
				style: "italic",
				url: "https://fonts.gstatic.com/s/instrumentsans/v1/pxigypc9vsFDm051Uf6KVwgkfoSbSnNPooZAN0lInHGpCWNE27lgU-XJojENut22kywN2u7YUwU.woff2",
				weight: "500",
			},
		],
	},
];
var css2 = [
	'.framer-CkOB6 .framer-styles-preset-1usrp2a:not(.rich-text-wrapper), .framer-CkOB6 .framer-styles-preset-1usrp2a.rich-text-wrapper h1 { --framer-font-family: "Instrument Sans", "Instrument Sans Placeholder", sans-serif; --framer-font-family-bold: "Instrument Sans", "Instrument Sans Placeholder", sans-serif; --framer-font-family-bold-italic: "Instrument Sans", "Instrument Sans Placeholder", sans-serif; --framer-font-family-italic: "Instrument Sans", "Instrument Sans Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 60px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 500; --framer-letter-spacing: -0.035em; --framer-line-height: 1.2em; --framer-paragraph-spacing: 0px; --framer-text-alignment: left; --framer-text-color: var(--token-38f68815-7867-4cb4-b7c3-02378b3e2eac, #0d0d0d); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }',
	'@media (max-width: 1199px) and (min-width: 810px) { .framer-CkOB6 .framer-styles-preset-1usrp2a:not(.rich-text-wrapper), .framer-CkOB6 .framer-styles-preset-1usrp2a.rich-text-wrapper h1 { --framer-font-family: "Instrument Sans", "Instrument Sans Placeholder", sans-serif; --framer-font-family-bold: "Instrument Sans", "Instrument Sans Placeholder", sans-serif; --framer-font-family-bold-italic: "Instrument Sans", "Instrument Sans Placeholder", sans-serif; --framer-font-family-italic: "Instrument Sans", "Instrument Sans Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 52px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 500; --framer-letter-spacing: -0.035em; --framer-line-height: 1.2em; --framer-paragraph-spacing: 0px; --framer-text-alignment: left; --framer-text-color: var(--token-38f68815-7867-4cb4-b7c3-02378b3e2eac, #0d0d0d); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
	'@media (max-width: 809px) and (min-width: 0px) { .framer-CkOB6 .framer-styles-preset-1usrp2a:not(.rich-text-wrapper), .framer-CkOB6 .framer-styles-preset-1usrp2a.rich-text-wrapper h1 { --framer-font-family: "Instrument Sans", "Instrument Sans Placeholder", sans-serif; --framer-font-family-bold: "Instrument Sans", "Instrument Sans Placeholder", sans-serif; --framer-font-family-bold-italic: "Instrument Sans", "Instrument Sans Placeholder", sans-serif; --framer-font-family-italic: "Instrument Sans", "Instrument Sans Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 42px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 500; --framer-letter-spacing: -0.035em; --framer-line-height: 1.2em; --framer-paragraph-spacing: 0px; --framer-text-alignment: left; --framer-text-color: var(--token-38f68815-7867-4cb4-b7c3-02378b3e2eac, #0d0d0d); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
];
var className2 = "framer-CkOB6";

// /:https://framerusercontent.com/modules/kE7qW2rz8DWyJGXRep7D/xcWXgsv8ZXoUm3vyNMYO/NbQT6L1iT.js
import { fontStore as fontStore2 } from "unframer";
fontStore2.loadFonts([
	"GF;Instrument Serif-italic",
	"GF;Instrument Serif-italic",
]);
var fonts3 = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "Instrument Serif",
				source: "google",
				style: "italic",
				url: "https://fonts.gstatic.com/s/instrumentserif/v4/jizHRFtNs2ka5fXjeivQ4LroWlx-6zATjnTNgNq55w.woff2",
				weight: "400",
			},
		],
	},
];
var css3 = [
	'.framer-cTmtE .framer-styles-preset-1xvyc0l:not(.rich-text-wrapper), .framer-cTmtE .framer-styles-preset-1xvyc0l.rich-text-wrapper h1 { --framer-font-family: "Instrument Serif", "Instrument Serif Placeholder", serif; --framer-font-family-italic: "Instrument Serif", "Instrument Serif Placeholder", serif; --framer-font-open-type-features: normal; --framer-font-size: 60px; --framer-font-style: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-italic: 400; --framer-letter-spacing: -0.035em; --framer-line-height: 1.2em; --framer-paragraph-spacing: 0px; --framer-text-alignment: left; --framer-text-color: var(--token-38f68815-7867-4cb4-b7c3-02378b3e2eac, #0d0d0d); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }',
	'@media (max-width: 1199px) and (min-width: 810px) { .framer-cTmtE .framer-styles-preset-1xvyc0l:not(.rich-text-wrapper), .framer-cTmtE .framer-styles-preset-1xvyc0l.rich-text-wrapper h1 { --framer-font-family: "Instrument Serif", "Instrument Serif Placeholder", serif; --framer-font-family-italic: "Instrument Serif", "Instrument Serif Placeholder", serif; --framer-font-open-type-features: normal; --framer-font-size: 52px; --framer-font-style: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-italic: 400; --framer-letter-spacing: -0.035em; --framer-line-height: 1.2em; --framer-paragraph-spacing: 0px; --framer-text-alignment: left; --framer-text-color: var(--token-38f68815-7867-4cb4-b7c3-02378b3e2eac, #0d0d0d); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
	'@media (max-width: 809px) and (min-width: 0px) { .framer-cTmtE .framer-styles-preset-1xvyc0l:not(.rich-text-wrapper), .framer-cTmtE .framer-styles-preset-1xvyc0l.rich-text-wrapper h1 { --framer-font-family: "Instrument Serif", "Instrument Serif Placeholder", serif; --framer-font-family-italic: "Instrument Serif", "Instrument Serif Placeholder", serif; --framer-font-open-type-features: normal; --framer-font-size: 42px; --framer-font-style: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-italic: 400; --framer-letter-spacing: -0.035em; --framer-line-height: 1.2em; --framer-paragraph-spacing: 0px; --framer-text-alignment: left; --framer-text-color: var(--token-38f68815-7867-4cb4-b7c3-02378b3e2eac, #0d0d0d); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
];
var className3 = "framer-cTmtE";

// /:https://framerusercontent.com/modules/kZu5MHqBkWLAHWEmDrGV/yXePt8lv5Dw0j3pqvyxu/njSozvrnr.js
import { fontStore as fontStore3 } from "unframer";
fontStore3.loadFonts([
	"FS;Satoshi-medium",
	"FS;Satoshi-bold",
	"FS;Satoshi-bold italic",
	"FS;Satoshi-medium italic",
]);
var fonts4 = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "Satoshi",
				source: "fontshare",
				style: "normal",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/P2LQKHE6KA6ZP4AAGN72KDWMHH6ZH3TA/ZC32TK2P7FPS5GFTL46EU6KQJA24ZYDB/7AHDUZ4A7LFLVFUIFSARGIWCRQJHISQP.woff2",
				weight: "500",
			},
			{
				family: "Satoshi",
				source: "fontshare",
				style: "normal",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/LAFFD4SDUCDVQEXFPDC7C53EQ4ZELWQI/PXCT3G6LO6ICM5I3NTYENYPWJAECAWDD/GHM6WVH6MILNYOOCXHXB5GTSGNTMGXZR.woff2",
				weight: "700",
			},
			{
				family: "Satoshi",
				source: "fontshare",
				style: "italic",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/CDEBEFT2R7XKNGXSBBLZGMY4MMHZG75P/HEVKDGQCYDZ7Z6CDVR2ZQGBCTUD6ZARH/BKWEE3VKGTFABE37K2DTH625VUSN2N35.woff2",
				weight: "700",
			},
			{
				family: "Satoshi",
				source: "fontshare",
				style: "italic",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/NID3I7RITWZSKXRCJGOCMP5NOADJK6IG/2HLHGD7OBTWCOHW64YXOE5KFXHU4KJHM/ZHME2QIRFR7UPJ47NLY27RCAFY44CKZJ.woff2",
				weight: "500",
			},
		],
	},
];
var css4 = [
	`.framer-eG2Ld .framer-styles-preset-14mden8:not(.rich-text-wrapper), .framer-eG2Ld .framer-styles-preset-14mden8.rich-text-wrapper p { --framer-font-family: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-bold: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-bold-italic: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-italic: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 20px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 500; --framer-letter-spacing: -0.025em; --framer-line-height: 1.5em; --framer-paragraph-spacing: 15px; --framer-text-alignment: left; --framer-text-color: var(--token-0e400885-4ad5-460c-800d-ba26ba3d28f7, #636363); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }`,
	`@media (max-width: 1099px) and (min-width: 810px) { .framer-eG2Ld .framer-styles-preset-14mden8:not(.rich-text-wrapper), .framer-eG2Ld .framer-styles-preset-14mden8.rich-text-wrapper p { --framer-font-family: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-bold: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-bold-italic: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-italic: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 18px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: -0.025em; --framer-line-height: 1.5em; --framer-paragraph-spacing: 15px; --framer-text-alignment: left; --framer-text-color: var(--token-0e400885-4ad5-460c-800d-ba26ba3d28f7, #636363); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }`,
	`@media (max-width: 809px) and (min-width: 0px) { .framer-eG2Ld .framer-styles-preset-14mden8:not(.rich-text-wrapper), .framer-eG2Ld .framer-styles-preset-14mden8.rich-text-wrapper p { --framer-font-family: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-bold: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-bold-italic: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-italic: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 17px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: -0.025em; --framer-line-height: 1.5em; --framer-paragraph-spacing: 15px; --framer-text-alignment: left; --framer-text-color: var(--token-0e400885-4ad5-460c-800d-ba26ba3d28f7, #636363); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }`,
];
var className4 = "framer-eG2Ld";

// /:https://framerusercontent.com/modules/kf0E2yq88EYQHtUZm0rB/8216dFjWd7zDyRCRk0FX/hL5g3kPjk.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	Link,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";

// /:https://framerusercontent.com/modules/zHxj9PxOxfygVJC0vsPR/1zxeUronKgVeCZyYIwih/sbfqMYLvJ.js
import { fontStore as fontStore4 } from "unframer";
fontStore4.loadFonts([
	"FS;Satoshi-medium",
	"FS;Satoshi-bold",
	"FS;Satoshi-bold italic",
	"FS;Satoshi-medium italic",
]);
var fonts5 = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "Satoshi",
				source: "fontshare",
				style: "normal",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/P2LQKHE6KA6ZP4AAGN72KDWMHH6ZH3TA/ZC32TK2P7FPS5GFTL46EU6KQJA24ZYDB/7AHDUZ4A7LFLVFUIFSARGIWCRQJHISQP.woff2",
				weight: "500",
			},
			{
				family: "Satoshi",
				source: "fontshare",
				style: "normal",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/LAFFD4SDUCDVQEXFPDC7C53EQ4ZELWQI/PXCT3G6LO6ICM5I3NTYENYPWJAECAWDD/GHM6WVH6MILNYOOCXHXB5GTSGNTMGXZR.woff2",
				weight: "700",
			},
			{
				family: "Satoshi",
				source: "fontshare",
				style: "italic",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/CDEBEFT2R7XKNGXSBBLZGMY4MMHZG75P/HEVKDGQCYDZ7Z6CDVR2ZQGBCTUD6ZARH/BKWEE3VKGTFABE37K2DTH625VUSN2N35.woff2",
				weight: "700",
			},
			{
				family: "Satoshi",
				source: "fontshare",
				style: "italic",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/NID3I7RITWZSKXRCJGOCMP5NOADJK6IG/2HLHGD7OBTWCOHW64YXOE5KFXHU4KJHM/ZHME2QIRFR7UPJ47NLY27RCAFY44CKZJ.woff2",
				weight: "500",
			},
		],
	},
];
var css5 = [
	`.framer-N2d5q .framer-styles-preset-1wx24gf:not(.rich-text-wrapper), .framer-N2d5q .framer-styles-preset-1wx24gf.rich-text-wrapper p { --framer-font-family: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-bold: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-bold-italic: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-italic: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 16px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 500; --framer-letter-spacing: -0.3px; --framer-line-height: 1.6em; --framer-paragraph-spacing: 20px; --framer-text-alignment: left; --framer-text-color: var(--token-38f68815-7867-4cb4-b7c3-02378b3e2eac, #0d0d0d); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }`,
	`@media (max-width: 1099px) and (min-width: 810px) { .framer-N2d5q .framer-styles-preset-1wx24gf:not(.rich-text-wrapper), .framer-N2d5q .framer-styles-preset-1wx24gf.rich-text-wrapper p { --framer-font-family: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-bold: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-bold-italic: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-italic: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 16px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: -0.03em; --framer-line-height: 1.5em; --framer-paragraph-spacing: 20px; --framer-text-alignment: left; --framer-text-color: var(--token-38f68815-7867-4cb4-b7c3-02378b3e2eac, #0d0d0d); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }`,
	`@media (max-width: 809px) and (min-width: 0px) { .framer-N2d5q .framer-styles-preset-1wx24gf:not(.rich-text-wrapper), .framer-N2d5q .framer-styles-preset-1wx24gf.rich-text-wrapper p { --framer-font-family: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-bold: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-bold-italic: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-italic: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 16px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: -0.03em; --framer-line-height: 1.5em; --framer-paragraph-spacing: 20px; --framer-text-alignment: left; --framer-text-color: var(--token-38f68815-7867-4cb4-b7c3-02378b3e2eac, #0d0d0d); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }`,
];
var className5 = "framer-N2d5q";

// /:https://framerusercontent.com/modules/kf0E2yq88EYQHtUZm0rB/8216dFjWd7zDyRCRk0FX/hL5g3kPjk.js
var enabledGestures = {
	HxD9XWJQo: {
		hover: true,
	},
	PGvMe3c3B: {
		hover: true,
	},
};
var cycleOrder = ["PGvMe3c3B", "HxD9XWJQo"];
var serializationHash = "framer-kwbBF";
var variantClassNames = {
	HxD9XWJQo: "framer-v-18ortwz",
	PGvMe3c3B: "framer-v-rfd8nt",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	damping: 56,
	delay: 0,
	mass: 1,
	stiffness: 400,
	type: "spring",
};
var transformTemplate1 = (_, t) => `translateX(-50%) ${t}`;
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Button: "PGvMe3c3B",
	White: "HxD9XWJQo",
};
var getProps = ({ height, id, link, newTab, text, width, ...props }) => {
	return {
		...props,
		Pb6WiuirB: text ?? props.Pb6WiuirB ?? "Kontakt",
		TnagmA8vA: link ?? props.TnagmA8vA,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "PGvMe3c3B",
		VVLyc9YCi: newTab ?? props.VVLyc9YCi,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className7,
		layoutId,
		variant,
		Pb6WiuirB,
		TnagmA8vA,
		VVLyc9YCi,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "PGvMe3c3B",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className5];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<Link
						href={TnagmA8vA}
						motionChild={true}
						nodeId={"PGvMe3c3B"}
						openInNewTab={VVLyc9YCi}
						scopeId={"hL5g3kPjk"}
						smoothScroll={false}
					>
						<motion.a
							{...restProps}
							{...gestureHandlers}
							className={`${cx(scopingClassNames, "framer-rfd8nt", className7, classNames)} framer-1rm9wuo`}
							data-framer-name={"Button"}
							layoutDependency={layoutDependency}
							layoutId={"PGvMe3c3B"}
							ref={refBinding}
							style={{
								backgroundColor: "rgb(13, 38, 102)",
								borderBottomLeftRadius: 14,
								borderBottomRightRadius: 14,
								borderTopLeftRadius: 14,
								borderTopRightRadius: 14,
								...style,
							}}
							variants={{
								HxD9XWJQo: {
									backgroundColor:
										"var(--token-c9b12220-87c9-4c8c-a21d-cbf1e21628af, rgb(255, 255, 255))",
								},
							}}
							{...addPropertyOverrides(
								{
									"HxD9XWJQo-hover": {
										"data-framer-name": void 0,
									},
									"PGvMe3c3B-hover": {
										"data-framer-name": void 0,
									},
									HxD9XWJQo: {
										"data-framer-name": "White",
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<motion.div
								className={"framer-6lcw6s"}
								data-framer-name={"Text Wrapper"}
								layoutDependency={layoutDependency}
								layoutId={"JmRqU_ZBB"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1ozjjt7"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"OgYugWjSn"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-c9b12220-87c9-4c8c-a21d-cbf1e21628af, rgb(255, 255, 255))",
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={Pb6WiuirB}
									variants={{
										HxD9XWJQo: {
											"--extracted-r6o4lv":
												"var(--token-38f68815-7867-4cb4-b7c3-02378b3e2eac, rgb(13, 13, 13))",
										},
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											"HxD9XWJQo-hover": {
												transformTemplate: transformTemplate1,
											},
											HxD9XWJQo: {
												children: (
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-1wx24gf"}
															data-styles-preset={"sbfqMYLvJ"}
															style={{
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-38f68815-7867-4cb4-b7c3-02378b3e2eac, rgb(13, 13, 13)))",
															}}
														>
															{"Contact Us"}
														</motion.p>
													</React.Fragment>
												),
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-1wx24gf"}
											data-styles-preset={"sbfqMYLvJ"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-c9b12220-87c9-4c8c-a21d-cbf1e21628af, rgb(255, 255, 255)))",
											}}
										>
											{"Contact Us"}
										</motion.p>
									</React.Fragment>
								</RichText>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1e641qf"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"IoM3e245I"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-c9b12220-87c9-4c8c-a21d-cbf1e21628af, rgb(255, 255, 255))",
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={Pb6WiuirB}
									variants={{
										HxD9XWJQo: {
											"--extracted-r6o4lv":
												"var(--token-38f68815-7867-4cb4-b7c3-02378b3e2eac, rgb(13, 13, 13))",
										},
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											HxD9XWJQo: {
												children: (
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-1wx24gf"}
															data-styles-preset={"sbfqMYLvJ"}
															style={{
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-38f68815-7867-4cb4-b7c3-02378b3e2eac, rgb(13, 13, 13)))",
															}}
														>
															{"Contact Us"}
														</motion.p>
													</React.Fragment>
												),
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-1wx24gf"}
											data-styles-preset={"sbfqMYLvJ"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-c9b12220-87c9-4c8c-a21d-cbf1e21628af, rgb(255, 255, 255)))",
											}}
										>
											{"Contact Us"}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
						</motion.a>
					</Link>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css6 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-kwbBF.framer-1rm9wuo, .framer-kwbBF .framer-1rm9wuo { display: block; }",
	".framer-kwbBF.framer-rfd8nt { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 12px 20px 12px 20px; position: relative; text-decoration: none; width: min-content; will-change: var(--framer-will-change-override, transform); }",
	".framer-kwbBF .framer-6lcw6s { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
	".framer-kwbBF .framer-1ozjjt7 { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-kwbBF .framer-1e641qf { bottom: -25px; flex: none; height: auto; left: 0px; position: absolute; white-space: pre; width: auto; z-index: 1; }",
	".framer-kwbBF.framer-v-rfd8nt.hover .framer-1ozjjt7 { position: absolute; right: 0px; top: -25px; z-index: 1; }",
	".framer-kwbBF.framer-v-rfd8nt.hover .framer-1e641qf, .framer-kwbBF.framer-v-18ortwz.hover .framer-1e641qf { bottom: unset; left: unset; position: relative; }",
	".framer-kwbBF.framer-v-18ortwz.hover .framer-1ozjjt7 { left: 49%; position: absolute; top: -25px; z-index: 1; }",
	...css5,
];
var FramerhL5g3kPjk = withCSS(Component, css6, "framer-kwbBF");
var stdin_default = FramerhL5g3kPjk;
FramerhL5g3kPjk.displayName = "Button";
FramerhL5g3kPjk.defaultProps = {
	height: 50,
	width: 93,
};
addPropertyControls(FramerhL5g3kPjk, {
	variant: {
		options: ["PGvMe3c3B", "HxD9XWJQo"],
		optionTitles: ["Button", "White"],
		title: "Variant",
		type: ControlType.Enum,
	},
	Pb6WiuirB: {
		defaultValue: "Kontakt",
		displayTextArea: false,
		title: "Text",
		type: ControlType.String,
	},
	TnagmA8vA: {
		title: "Link",
		type: ControlType.Link,
	},
	VVLyc9YCi: {
		defaultValue: false,
		title: "New Tab",
		type: ControlType.Boolean,
	},
});
addFonts(
	FramerhL5g3kPjk,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts5),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/ooPuPAKsfu2Vg2oedMcx/JbvV7U65PA1gf5XsmdEh/IjOYJsMtg.js
import { jsx as _jsx2, jsxs as _jsxs2 } from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	cx as cx2,
	getFontsFromSharedStyle as getFontsFromSharedStyle2,
	getLoadingLazyAtYPosition,
	Image,
	RichText as RichText2,
	useComponentViewport as useComponentViewport2,
	useLocaleInfo as useLocaleInfo2,
	useVariantState as useVariantState2,
	withCSS as withCSS2,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React2 from "react";
var serializationHash2 = "framer-s9t8v";
var variantClassNames2 = {
	zi5_ZH2wd: "framer-v-w3bvrl",
};
var transition12 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var transformTemplate12 = (_, t) => `translateY(-50%) ${t}`;
var Transition2 = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext2);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider value={contextValue}>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var Variants2 = motion2.create(React2.Fragment);
var getProps2 = ({ height, id, width, ...props }) => {
	return {
		...props,
	};
};
var createLayoutDependency2 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo2();
	const {
		style,
		className: className7,
		layoutId,
		variant,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		defaultVariant: "zi5_ZH2wd",
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const ref1 = React2.useRef(null);
	const defaultLayoutId = React2.useId();
	const sharedStyleClassNames = [className];
	const componentViewport = useComponentViewport2();
	return (
		<LayoutGroup2
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants2 animate={variants} initial={false}>
				<Transition2 value={transition12}>
					<motion2.div
						{...restProps}
						{...gestureHandlers}
						className={cx2(
							serializationHash2,
							...sharedStyleClassNames,
							"framer-w3bvrl",
							className7,
							classNames,
						)}
						data-framer-name={"Rating"}
						layoutDependency={layoutDependency}
						layoutId={"zi5_ZH2wd"}
						ref={ref !== null && ref !== void 0 ? ref : ref1}
						style={{
							...style,
						}}
					>
						<motion2.div
							className={"framer-1wk47hn"}
							data-framer-name={"Images-wrapper"}
							layoutDependency={layoutDependency}
							layoutId={"WJhlCnsMf"}
						>
							<Image
								background={{
									alt: "",
									fit: "fill",
									loading: getLoadingLazyAtYPosition(
										((componentViewport === null || componentViewport === void 0
											? void 0
											: componentViewport.y) || 0) +
											(0 +
												(((componentViewport === null ||
												componentViewport === void 0
													? void 0
													: componentViewport.height) || 44) -
													0 -
													44) /
													2) +
											0,
									),
									pixelHeight: 739,
									pixelWidth: 900,
									sizes: "44px",
									src: "https://framerusercontent.com/images/rZf6E37UWgU9EKpV2BikauvVI.webp",
									srcSet:
										"https://framerusercontent.com/images/rZf6E37UWgU9EKpV2BikauvVI.webp?scale-down-to=512 512w,https://framerusercontent.com/images/rZf6E37UWgU9EKpV2BikauvVI.webp 900w",
								}}
								className={"framer-1s40mmj"}
								data-border={true}
								data-framer-name={"Image"}
								layoutDependency={layoutDependency}
								layoutId={"NqI9x0xJN"}
								style={{
									"--border-bottom-width": "3px",
									"--border-color":
										"var(--token-c9b12220-87c9-4c8c-a21d-cbf1e21628af, rgb(255, 255, 255))",
									"--border-left-width": "3px",
									"--border-right-width": "3px",
									"--border-style": "solid",
									"--border-top-width": "3px",
									borderBottomLeftRadius: 200,
									borderBottomRightRadius: 200,
									borderTopLeftRadius: 200,
									borderTopRightRadius: 200,
								}}
							/>
							<Image
								background={{
									alt: "",
									fit: "fill",
									loading: getLoadingLazyAtYPosition(
										((componentViewport === null || componentViewport === void 0
											? void 0
											: componentViewport.y) || 0) +
											(0 +
												(((componentViewport === null ||
												componentViewport === void 0
													? void 0
													: componentViewport.height) || 44) -
													0 -
													44) /
													2) +
											-0.3188405797101339,
									),
									pixelHeight: 523,
									pixelWidth: 592,
									sizes: "44px",
									src: "https://framerusercontent.com/images/oQlToJVMUOwUCkrv9WSgaF21Ks.webp",
									srcSet:
										"https://framerusercontent.com/images/oQlToJVMUOwUCkrv9WSgaF21Ks.webp?scale-down-to=512 512w,https://framerusercontent.com/images/oQlToJVMUOwUCkrv9WSgaF21Ks.webp 592w",
								}}
								className={"framer-16ahua"}
								data-border={true}
								data-framer-name={"Image"}
								layoutDependency={layoutDependency}
								layoutId={"juV4sfpEw"}
								style={{
									"--border-bottom-width": "3px",
									"--border-color":
										"var(--token-c9b12220-87c9-4c8c-a21d-cbf1e21628af, rgb(255, 255, 255))",
									"--border-left-width": "3px",
									"--border-right-width": "3px",
									"--border-style": "solid",
									"--border-top-width": "3px",
									borderBottomLeftRadius: 200,
									borderBottomRightRadius: 200,
									borderTopLeftRadius: 200,
									borderTopRightRadius: 200,
								}}
								transformTemplate={transformTemplate12}
							/>
							<Image
								background={{
									alt: "",
									fit: "fill",
									loading: getLoadingLazyAtYPosition(
										((componentViewport === null || componentViewport === void 0
											? void 0
											: componentViewport.y) || 0) +
											(0 +
												(((componentViewport === null ||
												componentViewport === void 0
													? void 0
													: componentViewport.height) || 44) -
													0 -
													44) /
													2) +
											-0.3188405797101339,
									),
									pixelHeight: 280,
									pixelWidth: 340,
									positionX: "44.4%",
									positionY: "31.1%",
									src: "https://framerusercontent.com/images/xpgxvdiadtUUi4pkJ3GIibpftVg.jpg",
								}}
								className={"framer-9zh259"}
								data-border={true}
								data-framer-name={"Image"}
								layoutDependency={layoutDependency}
								layoutId={"CH4mz4TEB"}
								style={{
									"--border-bottom-width": "3px",
									"--border-color":
										"var(--token-c9b12220-87c9-4c8c-a21d-cbf1e21628af, rgb(255, 255, 255))",
									"--border-left-width": "3px",
									"--border-right-width": "3px",
									"--border-style": "solid",
									"--border-top-width": "3px",
									borderBottomLeftRadius: 200,
									borderBottomRightRadius: 200,
									borderTopLeftRadius: 200,
									borderTopRightRadius: 200,
								}}
								transformTemplate={transformTemplate12}
							/>
						</motion2.div>
						<motion2.div
							className={"framer-1uri8v2"}
							data-framer-name={"Stars"}
							layoutDependency={layoutDependency}
							layoutId={"JEhn59jMy"}
						>
							<motion2.div
								className={"framer-2j64w0"}
								data-framer-name={"Stars Item"}
								layoutDependency={layoutDependency}
								layoutId={"j7PUF9gFz"}
							>
								<Image
									background={{
										alt: "",
										fit: "fill",
										loading: getLoadingLazyAtYPosition(
											((componentViewport === null ||
											componentViewport === void 0
												? void 0
												: componentViewport.y) || 0) +
												(0 +
													(((componentViewport === null ||
													componentViewport === void 0
														? void 0
														: componentViewport.height) || 44) -
														0 -
														35.8) /
														2) +
												0 +
												0 +
												0,
										),
										pixelHeight: 800,
										pixelWidth: 800,
										src: "https://framerusercontent.com/images/SSfcKMLPUGz1xqJLBa9a4Gz54U.svg",
									}}
									className={"framer-1fnf29v"}
									data-framer-name={"Image"}
									layoutDependency={layoutDependency}
									layoutId={"n0IuZyVMS"}
								/>
								<Image
									background={{
										alt: "",
										fit: "fill",
										loading: getLoadingLazyAtYPosition(
											((componentViewport === null ||
											componentViewport === void 0
												? void 0
												: componentViewport.y) || 0) +
												(0 +
													(((componentViewport === null ||
													componentViewport === void 0
														? void 0
														: componentViewport.height) || 44) -
														0 -
														35.8) /
														2) +
												0 +
												0 +
												0,
										),
										pixelHeight: 800,
										pixelWidth: 800,
										src: "https://framerusercontent.com/images/SSfcKMLPUGz1xqJLBa9a4Gz54U.svg",
									}}
									className={"framer-bovnrf"}
									data-framer-name={"Image"}
									layoutDependency={layoutDependency}
									layoutId={"kaf7dNbvN"}
								/>
								<Image
									background={{
										alt: "",
										fit: "fill",
										loading: getLoadingLazyAtYPosition(
											((componentViewport === null ||
											componentViewport === void 0
												? void 0
												: componentViewport.y) || 0) +
												(0 +
													(((componentViewport === null ||
													componentViewport === void 0
														? void 0
														: componentViewport.height) || 44) -
														0 -
														35.8) /
														2) +
												0 +
												0 +
												0,
										),
										pixelHeight: 800,
										pixelWidth: 800,
										src: "https://framerusercontent.com/images/SSfcKMLPUGz1xqJLBa9a4Gz54U.svg",
									}}
									className={"framer-190ta1l"}
									data-framer-name={"Image"}
									layoutDependency={layoutDependency}
									layoutId={"eHnRHSe9Z"}
								/>
								<Image
									background={{
										alt: "",
										fit: "fill",
										loading: getLoadingLazyAtYPosition(
											((componentViewport === null ||
											componentViewport === void 0
												? void 0
												: componentViewport.y) || 0) +
												(0 +
													(((componentViewport === null ||
													componentViewport === void 0
														? void 0
														: componentViewport.height) || 44) -
														0 -
														35.8) /
														2) +
												0 +
												0 +
												0,
										),
										pixelHeight: 800,
										pixelWidth: 800,
										src: "https://framerusercontent.com/images/SSfcKMLPUGz1xqJLBa9a4Gz54U.svg",
									}}
									className={"framer-hknkm6"}
									data-framer-name={"Image"}
									layoutDependency={layoutDependency}
									layoutId={"CAywW6Mni"}
								/>
								<Image
									background={{
										alt: "",
										fit: "fill",
										loading: getLoadingLazyAtYPosition(
											((componentViewport === null ||
											componentViewport === void 0
												? void 0
												: componentViewport.y) || 0) +
												(0 +
													(((componentViewport === null ||
													componentViewport === void 0
														? void 0
														: componentViewport.height) || 44) -
														0 -
														35.8) /
														2) +
												0 +
												0 +
												0,
										),
										pixelHeight: 800,
										pixelWidth: 800,
										src: "https://framerusercontent.com/images/SSfcKMLPUGz1xqJLBa9a4Gz54U.svg",
									}}
									className={"framer-b5o1xf"}
									data-framer-name={"Image"}
									layoutDependency={layoutDependency}
									layoutId={"tnoYviabB"}
								/>
							</motion2.div>
							<RichText2
								__fromCanvasComponent={true}
								className={"framer-1itpbkd"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"JT3ncTwJt"}
								style={{
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React2.Fragment>
									<motion2.p
										className={"framer-styles-preset-1dca42r"}
										data-styles-preset={"mkY39OzE0"}
									>
										{"23,450 Reviews"}
									</motion2.p>
								</React2.Fragment>
							</RichText2>
						</motion2.div>
					</motion2.div>
				</Transition2>
			</Variants2>
		</LayoutGroup2>
	);
});
var css7 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-s9t8v.framer-1tij1p3, .framer-s9t8v .framer-1tij1p3 { display: block; }",
	".framer-s9t8v.framer-w3bvrl { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 12px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
	".framer-s9t8v .framer-1wk47hn { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 105px; }",
	".framer-s9t8v .framer-1s40mmj { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 44px); overflow: hidden; position: relative; width: 44px; will-change: var(--framer-will-change-override, transform); }",
	".framer-s9t8v .framer-16ahua { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 44px); left: 30px; overflow: hidden; position: absolute; top: 49%; width: 44px; will-change: var(--framer-will-change-override, transform); z-index: 1; }",
	".framer-s9t8v .framer-9zh259 { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 44px); left: 60px; overflow: hidden; position: absolute; top: 49%; width: 44px; will-change: var(--framer-will-change-override, transform); z-index: 1; }",
	".framer-s9t8v .framer-1uri8v2 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 7px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
	".framer-s9t8v .framer-2j64w0 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 2px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
	".framer-s9t8v .framer-1fnf29v, .framer-s9t8v .framer-bovnrf, .framer-s9t8v .framer-190ta1l, .framer-s9t8v .framer-hknkm6, .framer-s9t8v .framer-b5o1xf { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 12px); overflow: hidden; position: relative; width: 12px; }",
	".framer-s9t8v .framer-1itpbkd { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-s9t8v.framer-w3bvrl, .framer-s9t8v .framer-1wk47hn, .framer-s9t8v .framer-1uri8v2, .framer-s9t8v .framer-2j64w0 { gap: 0px; } .framer-s9t8v.framer-w3bvrl > * { margin: 0px; margin-left: calc(12px / 2); margin-right: calc(12px / 2); } .framer-s9t8v.framer-w3bvrl > :first-child, .framer-s9t8v .framer-1wk47hn > :first-child, .framer-s9t8v .framer-2j64w0 > :first-child { margin-left: 0px; } .framer-s9t8v.framer-w3bvrl > :last-child, .framer-s9t8v .framer-1wk47hn > :last-child, .framer-s9t8v .framer-2j64w0 > :last-child { margin-right: 0px; } .framer-s9t8v .framer-1wk47hn > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-s9t8v .framer-1uri8v2 > * { margin: 0px; margin-bottom: calc(7px / 2); margin-top: calc(7px / 2); } .framer-s9t8v .framer-1uri8v2 > :first-child { margin-top: 0px; } .framer-s9t8v .framer-1uri8v2 > :last-child { margin-bottom: 0px; } .framer-s9t8v .framer-2j64w0 > * { margin: 0px; margin-left: calc(2px / 2); margin-right: calc(2px / 2); } }",
	...css,
	'.framer-s9t8v[data-border="true"]::after, .framer-s9t8v [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerIjOYJsMtg = withCSS2(Component2, css7, "framer-s9t8v");
var stdin_default2 = FramerIjOYJsMtg;
FramerIjOYJsMtg.displayName = "Utility/Rating";
FramerIjOYJsMtg.defaultProps = {
	height: 44,
	width: 212,
};
addFonts2(
	FramerIjOYJsMtg,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle2(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/Ae95dedDxpOmAELc4juS/vQ9GqW3oekaBbDWq17vA/lHqsgp0cE.js
import { jsx as _jsx3, jsxs as _jsxs3 } from "react/jsx-runtime";
import {
	addFonts as addFonts3,
	addPropertyControls as addPropertyControls2,
	ControlType as ControlType2,
	cx as cx3,
	getFontsFromSharedStyle as getFontsFromSharedStyle3,
	getLoadingLazyAtYPosition as getLoadingLazyAtYPosition2,
	Image as Image2,
	RichText as RichText3,
	useComponentViewport as useComponentViewport3,
	useLocaleInfo as useLocaleInfo3,
	useVariantState as useVariantState3,
	withCSS as withCSS3,
} from "unframer";
import {
	LayoutGroup as LayoutGroup3,
	motion as motion3,
	MotionConfigContext as MotionConfigContext3,
} from "unframer";
import * as React3 from "react";

// /:https://framerusercontent.com/modules/c5shlEImDZljUifAphD0/fkJpOPPr6rJCF0z4mF7Q/sbfqMYLvJ.js
import { fontStore as fontStore5 } from "unframer";
fontStore5.loadFonts([
	"FS;Satoshi-medium",
	"FS;Satoshi-bold",
	"FS;Satoshi-bold italic",
	"FS;Satoshi-medium italic",
]);
var fonts6 = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "Satoshi",
				source: "fontshare",
				style: "normal",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/P2LQKHE6KA6ZP4AAGN72KDWMHH6ZH3TA/ZC32TK2P7FPS5GFTL46EU6KQJA24ZYDB/7AHDUZ4A7LFLVFUIFSARGIWCRQJHISQP.woff2",
				weight: "500",
			},
			{
				family: "Satoshi",
				source: "fontshare",
				style: "normal",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/LAFFD4SDUCDVQEXFPDC7C53EQ4ZELWQI/PXCT3G6LO6ICM5I3NTYENYPWJAECAWDD/GHM6WVH6MILNYOOCXHXB5GTSGNTMGXZR.woff2",
				weight: "700",
			},
			{
				family: "Satoshi",
				source: "fontshare",
				style: "italic",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/CDEBEFT2R7XKNGXSBBLZGMY4MMHZG75P/HEVKDGQCYDZ7Z6CDVR2ZQGBCTUD6ZARH/BKWEE3VKGTFABE37K2DTH625VUSN2N35.woff2",
				weight: "700",
			},
			{
				family: "Satoshi",
				source: "fontshare",
				style: "italic",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/NID3I7RITWZSKXRCJGOCMP5NOADJK6IG/2HLHGD7OBTWCOHW64YXOE5KFXHU4KJHM/ZHME2QIRFR7UPJ47NLY27RCAFY44CKZJ.woff2",
				weight: "500",
			},
		],
	},
];
var css8 = [
	`.framer-N2d5q .framer-styles-preset-1wx24gf:not(.rich-text-wrapper), .framer-N2d5q .framer-styles-preset-1wx24gf.rich-text-wrapper p { --framer-font-family: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-bold: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-bold-italic: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-italic: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 16px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 500; --framer-letter-spacing: -0.3px; --framer-line-height: 1.6em; --framer-paragraph-spacing: 20px; --framer-text-alignment: left; --framer-text-color: var(--token-38f68815-7867-4cb4-b7c3-02378b3e2eac, #0d0d0d); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }`,
	`@media (max-width: 1099px) and (min-width: 810px) { .framer-N2d5q .framer-styles-preset-1wx24gf:not(.rich-text-wrapper), .framer-N2d5q .framer-styles-preset-1wx24gf.rich-text-wrapper p { --framer-font-family: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-bold: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-bold-italic: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-italic: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 16px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: -0.03em; --framer-line-height: 1.5em; --framer-paragraph-spacing: 20px; --framer-text-alignment: left; --framer-text-color: var(--token-38f68815-7867-4cb4-b7c3-02378b3e2eac, #0d0d0d); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }`,
	`@media (max-width: 809px) and (min-width: 0px) { .framer-N2d5q .framer-styles-preset-1wx24gf:not(.rich-text-wrapper), .framer-N2d5q .framer-styles-preset-1wx24gf.rich-text-wrapper p { --framer-font-family: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-bold: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-bold-italic: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-italic: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 16px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: -0.03em; --framer-line-height: 1.5em; --framer-paragraph-spacing: 20px; --framer-text-alignment: left; --framer-text-color: var(--token-38f68815-7867-4cb4-b7c3-02378b3e2eac, #0d0d0d); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }`,
];
var className6 = "framer-N2d5q";

// /:https://framerusercontent.com/modules/Ae95dedDxpOmAELc4juS/vQ9GqW3oekaBbDWq17vA/lHqsgp0cE.js
var serializationHash3 = "framer-mHqlO";
var variantClassNames3 = {
	oVgjznMrN: "framer-v-1k6ynfb",
};
var transition13 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition3 = ({ value, children }) => {
	const config = React3.useContext(MotionConfigContext3);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React3.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext3.Provider value={contextValue}>
			{children}
		</MotionConfigContext3.Provider>
	);
};
var Variants3 = motion3.create(React3.Fragment);
var getProps3 = ({ height, icon, id, text, width, ...props }) => {
	var _ref, _ref1;
	return {
		...props,
		aiNqP760d:
			(_ref = text !== null && text !== void 0 ? text : props.aiNqP760d) !==
				null && _ref !== void 0
				? _ref
				: "4.9/5 Reviews",
		mHBqjsGa3:
			(_ref1 = icon !== null && icon !== void 0 ? icon : props.mHBqjsGa3) !==
				null && _ref1 !== void 0
				? _ref1
				: {
						src: "https://framerusercontent.com/images/j3k7nSqYEmap6xSncSed7WwuXk.svg",
					},
	};
};
var createLayoutDependency3 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component3 = /* @__PURE__ */ React3.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo3();
	const {
		style,
		className: className7,
		layoutId,
		variant,
		mHBqjsGa3,
		aiNqP760d,
		...restProps
	} = getProps3(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState3({
		defaultVariant: "oVgjznMrN",
		variant,
		variantClassNames: variantClassNames3,
	});
	const layoutDependency = createLayoutDependency3(props, variants);
	const ref1 = React3.useRef(null);
	const defaultLayoutId = React3.useId();
	const sharedStyleClassNames = [className6];
	const componentViewport = useComponentViewport3();
	return (
		<LayoutGroup3
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants3 animate={variants} initial={false}>
				<Transition3 value={transition13}>
					<motion3.div
						{...restProps}
						{...gestureHandlers}
						className={cx3(
							serializationHash3,
							...sharedStyleClassNames,
							"framer-1k6ynfb",
							className7,
							classNames,
						)}
						data-framer-name={"Rating-Tag"}
						layoutDependency={layoutDependency}
						layoutId={"oVgjznMrN"}
						ref={ref !== null && ref !== void 0 ? ref : ref1}
						style={{
							backgroundColor: "rgba(46, 105, 255, 0.04)",
							borderBottomLeftRadius: 1e3,
							borderBottomRightRadius: 1e3,
							borderTopLeftRadius: 1e3,
							borderTopRightRadius: 1e3,
							...style,
						}}
					>
						<motion3.div
							className={"framer-5pf8mm"}
							data-framer-name={"Icon Wrapper"}
							layoutDependency={layoutDependency}
							layoutId={"VbPkbYIxl"}
							style={{
								backgroundColor:
									"var(--token-37c73a71-ed98-4730-86d9-6e0a52d466b3, rgb(46, 105, 255))",
								borderBottomLeftRadius: 1e3,
								borderBottomRightRadius: 1e3,
								borderTopLeftRadius: 1e3,
								borderTopRightRadius: 1e3,
							}}
						>
							<Image2
								background={{
									alt: "",
									fit: "fill",
									loading: getLoadingLazyAtYPosition2(
										((componentViewport === null || componentViewport === void 0
											? void 0
											: componentViewport.y) || 0) +
											(5 +
												(((componentViewport === null ||
												componentViewport === void 0
													? void 0
													: componentViewport.height) || 42) -
													10 -
													32) /
													2) +
											8,
									),
									pixelHeight: 800,
									pixelWidth: 800,
									sizes: "16px",
									...toResponsiveImage(mHBqjsGa3),
									...{
										positionX: "center",
										positionY: "center",
									},
								}}
								className={"framer-15yns49"}
								data-framer-name={"Icon"}
								layoutDependency={layoutDependency}
								layoutId={"ApOHLCcNx"}
							/>
						</motion3.div>
						<RichText3
							__fromCanvasComponent={true}
							className={"framer-1gpv0pb"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"d7Oo3wFzY"}
							style={{
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							text={aiNqP760d}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React3.Fragment>
								<motion3.p
									className={"framer-styles-preset-1wx24gf"}
									data-styles-preset={"sbfqMYLvJ"}
								>
									{"4.9/5 Reviews"}
								</motion3.p>
							</React3.Fragment>
						</RichText3>
					</motion3.div>
				</Transition3>
			</Variants3>
		</LayoutGroup3>
	);
});
var css9 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-mHqlO.framer-bjlq67, .framer-mHqlO .framer-bjlq67 { display: block; }",
	".framer-mHqlO.framer-1k6ynfb { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 5px 18px 5px 5px; position: relative; width: min-content; will-change: var(--framer-will-change-override, transform); }",
	".framer-mHqlO .framer-5pf8mm { align-content: center; align-items: center; aspect-ratio: 1 / 1; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: var(--framer-aspect-ratio-supported, 32px); justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 32px; will-change: var(--framer-will-change-override, transform); }",
	".framer-mHqlO .framer-15yns49 { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 16px); overflow: hidden; position: relative; width: 16px; }",
	".framer-mHqlO .framer-1gpv0pb { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-mHqlO.framer-1k6ynfb, .framer-mHqlO .framer-5pf8mm { gap: 0px; } .framer-mHqlO.framer-1k6ynfb > *, .framer-mHqlO .framer-5pf8mm > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-mHqlO.framer-1k6ynfb > :first-child, .framer-mHqlO .framer-5pf8mm > :first-child { margin-left: 0px; } .framer-mHqlO.framer-1k6ynfb > :last-child, .framer-mHqlO .framer-5pf8mm > :last-child { margin-right: 0px; } }",
	...css8,
];
var FramerlHqsgp0cE = withCSS3(Component3, css9, "framer-mHqlO");
var stdin_default3 = FramerlHqsgp0cE;
FramerlHqsgp0cE.displayName = "Rating-Tag";
FramerlHqsgp0cE.defaultProps = {
	height: 42,
	width: 162,
};
addPropertyControls2(FramerlHqsgp0cE, {
	mHBqjsGa3: {
		__defaultAssetReference:
			"data:framer/asset-reference,j3k7nSqYEmap6xSncSed7WwuXk.svg?originalFilename=star-svgrepo-com+%288%29.svg&preferredSize=auto",
		title: "Icon",
		type: ControlType2.ResponsiveImage,
	},
	aiNqP760d: {
		defaultValue: "4.9/5 Reviews",
		displayTextArea: false,
		title: "Text",
		type: ControlType2.String,
	},
});
addFonts3(
	FramerlHqsgp0cE,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle3(fonts6),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/1aSY1Lif3VzM4GvYmEkn/OetkHbKoEQPl2GP1n1sW/tnMZEkN8f.js
var RatingTagFonts = getFonts(stdin_default3);
var SmartComponentScopedContainerWithFXWithOptimizedAppearEffect =
	withOptimizedAppearEffect(withFX(SmartComponentScopedContainer));
var MotionDivWithFXWithOptimizedAppearEffect = withOptimizedAppearEffect(
	withFX(motion4.div),
);
var RichTextWithFXWithOptimizedAppearEffect = withOptimizedAppearEffect(
	withFX(RichText4),
);
var ButtonFonts = getFonts(stdin_default);
var UtilityRatingFonts = getFonts(stdin_default2);
var ImageWithFXWithOptimizedAppearEffect = withOptimizedAppearEffect(
	withFX(Image3),
);
var serializationHash4 = "framer-GGOxY";
var variantClassNames4 = {
	w_nscZeRQ: "framer-v-2nahyi",
};
var transition14 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var transition2 = {
	damping: 58,
	delay: 0.2,
	mass: 1,
	stiffness: 400,
	type: "spring",
};
var animation = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition2,
	x: 0,
	y: 0,
};
var animation1 = {
	opacity: 1e-3,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 18,
};
var transition3 = {
	damping: 58,
	delay: 0.4,
	mass: 1,
	stiffness: 400,
	type: "spring",
};
var animation2 = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition3,
	x: 0,
	y: 0,
};
var animation3 = {
	opacity: 1e-3,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 0,
};
var transition4 = {
	damping: 58,
	delay: 0.5,
	mass: 1,
	stiffness: 400,
	type: "spring",
};
var animation4 = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition4,
	x: 0,
	y: 0,
};
var animation5 = {
	opacity: 1e-3,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 0.9,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 28,
};
var Transition4 = ({ value, children }) => {
	const config = React4.useContext(MotionConfigContext4);
	const transition = value ?? config.transition;
	const contextValue = React4.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext4.Provider value={contextValue}>
			{children}
		</MotionConfigContext4.Provider>
	);
};
var Variants4 = motion4.create(React4.Fragment);
var getProps4 = ({ height, id, width, ...props }) => {
	return {
		...props,
	};
};
var createLayoutDependency4 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component4 = /* @__PURE__ */ React4.forwardRef(function (props, ref) {
	const fallbackRef = useRef4(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React4.useId();
	const { activeLocale, setLocale } = useLocaleInfo4();
	const componentViewport = useComponentViewport4();
	const {
		style,
		className: className7,
		layoutId,
		variant,
		...restProps
	} = getProps4(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState4({
		defaultVariant: "w_nscZeRQ",
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames4,
	});
	const layoutDependency = createLayoutDependency4(props, variants);
	const sharedStyleClassNames = [className2, className3, className4];
	const scopingClassNames = cx4(serializationHash4, ...sharedStyleClassNames);
	const router = useRouter();
	return (
		<LayoutGroup4 id={layoutId ?? defaultLayoutId}>
			<Variants4 animate={variants} initial={false}>
				<Transition4 value={transition14}>
					<motion4.div
						{...restProps}
						{...gestureHandlers}
						className={cx4(
							scopingClassNames,
							"framer-2nahyi",
							className7,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"w_nscZeRQ"}
						ref={refBinding}
						style={{
							...style,
						}}
					>
						<motion4.div
							className={"framer-14z3i77"}
							data-framer-name={"Main-wrapper"}
							layoutDependency={layoutDependency}
							layoutId={"GBRbjErRZ"}
						>
							<motion4.div
								className={"framer-4fg36"}
								data-framer-name={"Text-content-Wrapper"}
								layoutDependency={layoutDependency}
								layoutId={"P_mag5k1q"}
							>
								<ComponentViewportProvider height={42}>
									<SmartComponentScopedContainerWithFXWithOptimizedAppearEffect
										__perspectiveFX={false}
										__smartComponentFX={true}
										__targetOpacity={1}
										animate={animation}
										className={"framer-4q0li5-container"}
										data-framer-appear-id={"4q0li5"}
										data-framer-name={"Hero-Tag"}
										initial={animation1}
										layoutDependency={layoutDependency}
										layoutId={"y2I0U0cUX-container"}
										name={"Hero-Tag"}
										nodeId={"y2I0U0cUX"}
										optimized={true}
										rendersWithMotion={true}
										scopeId={"tnMZEkN8f"}
									>
										{_jsx4(stdin_default3, {
											aiNqP760d: "4.9/5 Reviews",
											height: "100%",
											id: "y2I0U0cUX",
											layoutId: "y2I0U0cUX",
											name: "Hero-Tag",
											width: "100%",
										})}
									</SmartComponentScopedContainerWithFXWithOptimizedAppearEffect>
								</ComponentViewportProvider>
								<motion4.div
									className={"framer-oey1vc"}
									data-framer-name={"Text-Wrapper"}
									layoutDependency={layoutDependency}
									layoutId={"q1XDHAPB2"}
								>
									<MotionDivWithFXWithOptimizedAppearEffect
										__perspectiveFX={false}
										__smartComponentFX={true}
										__targetOpacity={1}
										animate={animation}
										className={"framer-132nqf1"}
										data-framer-appear-id={"132nqf1"}
										data-framer-name={"Heading-wrapper"}
										initial={animation1}
										layoutDependency={layoutDependency}
										layoutId={"oHDHmyEFb"}
										optimized={true}
									>
										<RichText4
											__fromCanvasComponent={true}
											className={"framer-1cr8m3j"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"VhaIbqgqT"}
											style={{
												"--framer-link-text-color": "rgb(0, 153, 255)",
												"--framer-link-text-decoration": "underline",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React4.Fragment>
												<motion4.h1
													className={"framer-styles-preset-1usrp2a"}
													data-styles-preset={"IBuebZNpT"}
													style={{
														"--framer-text-alignment": "center",
													}}
												>
													{"Save your "}
												</motion4.h1>
											</React4.Fragment>
										</RichText4>
										<RichText4
											__fromCanvasComponent={true}
											className={"framer-9ahu6w"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"JiWqCrptK"}
											style={{
												"--framer-link-text-color": "rgb(0, 153, 255)",
												"--framer-link-text-decoration": "underline",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React4.Fragment>
												<motion4.h1
													className={"framer-styles-preset-1usrp2a"}
													data-styles-preset={"IBuebZNpT"}
													style={{
														"--framer-text-alignment": "center",
													}}
												>
													{"Money"}
												</motion4.h1>
											</React4.Fragment>
										</RichText4>
										<RichText4
											__fromCanvasComponent={true}
											className={"framer-zb8u71"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"q28Igo9Jz"}
											style={{
												"--framer-link-text-color": "rgb(0, 153, 255)",
												"--framer-link-text-decoration": "underline",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React4.Fragment>
												<motion4.h1
													className={"framer-styles-preset-1usrp2a"}
													data-styles-preset={"IBuebZNpT"}
													style={{
														"--framer-text-alignment": "center",
													}}
												>
													{"with"}
												</motion4.h1>
											</React4.Fragment>
										</RichText4>
										<RichText4
											__fromCanvasComponent={true}
											className={"framer-zh48yb"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"HqsXP12c1"}
											style={{
												"--framer-link-text-color": "rgb(0, 153, 255)",
												"--framer-link-text-decoration": "underline",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React4.Fragment>
												<motion4.h1
													className={"framer-styles-preset-1usrp2a"}
													data-styles-preset={"IBuebZNpT"}
													style={{
														"--framer-text-alignment": "center",
													}}
												>
													{"quality"}
												</motion4.h1>
											</React4.Fragment>
										</RichText4>
										<RichText4
											__fromCanvasComponent={true}
											className={"framer-yklocc"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"tRDD0d5zL"}
											style={{
												"--framer-link-text-color": "rgb(0, 153, 255)",
												"--framer-link-text-decoration": "underline",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React4.Fragment>
												<motion4.h1
													className={"framer-styles-preset-1usrp2a"}
													data-styles-preset={"IBuebZNpT"}
													style={{
														"--framer-text-alignment": "center",
													}}
												>
													{"&"}
												</motion4.h1>
											</React4.Fragment>
										</RichText4>
										<RichText4
											__fromCanvasComponent={true}
											className={"framer-19cjn1m"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"nDLw37dkr"}
											style={{
												"--framer-link-text-color": "rgb(0, 153, 255)",
												"--framer-link-text-decoration": "underline",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React4.Fragment>
												<motion4.h1
													className={"framer-styles-preset-1xvyc0l"}
													data-styles-preset={"NbQT6L1iT"}
													style={{
														"--framer-text-alignment": "center",
													}}
												>
													{"trust"}
												</motion4.h1>
											</React4.Fragment>
										</RichText4>
									</MotionDivWithFXWithOptimizedAppearEffect>
									<RichTextWithFXWithOptimizedAppearEffect
										__fromCanvasComponent={true}
										__perspectiveFX={false}
										__smartComponentFX={true}
										__targetOpacity={1}
										animate={animation}
										className={"framer-456sa0"}
										data-framer-appear-id={"456sa0"}
										fonts={["Inter"]}
										initial={animation1}
										layoutDependency={layoutDependency}
										layoutId={"Q341czmKL"}
										optimized={true}
										style={{
											"--extracted-r6o4lv":
												"var(--token-e4bee715-1a76-4d52-94a9-54840079c030, rgb(82, 82, 82))",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React4.Fragment>
											<motion4.p
												className={"framer-styles-preset-14mden8"}
												data-styles-preset={"njSozvrnr"}
												style={{
													"--framer-text-alignment": "center",
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-e4bee715-1a76-4d52-94a9-54840079c030, rgb(82, 82, 82)))",
												}}
											>
												{
													"We provide the tools and insights you need to enhance performance and achieve results."
												}
											</motion4.p>
										</React4.Fragment>
									</RichTextWithFXWithOptimizedAppearEffect>
								</motion4.div>
							</motion4.div>
							<MotionDivWithFXWithOptimizedAppearEffect
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={1}
								animate={animation2}
								className={"framer-1acfzhu"}
								data-framer-appear-id={"1acfzhu"}
								data-framer-name={"Buttons-wrapper"}
								initial={animation3}
								layoutDependency={layoutDependency}
								layoutId={"EkhNWoqX6"}
								optimized={true}
							>
								<ResolveLinks
									links={[
										{
											href: {
												webPageId: "Ml_0tdCB6",
											},
											implicitPathVariables: void 0,
										},
									]}
								>
									{(resolvedLinks) => (
										<ComponentViewportProvider height={50}>
											<SmartComponentScopedContainer
												className={"framer-1s4s09b-container"}
												data-framer-name={"Button"}
												layoutDependency={layoutDependency}
												layoutId={"IKgafMx9A-container"}
												name={"Button"}
												nodeId={"IKgafMx9A"}
												rendersWithMotion={true}
												scopeId={"tnMZEkN8f"}
											>
												{_jsx4(stdin_default, {
													height: "100%",
													id: "IKgafMx9A",
													layoutId: "IKgafMx9A",
													name: "Button",
													Pb6WiuirB: "Kontakt",
													TnagmA8vA: resolvedLinks[0],
													variant: "PGvMe3c3B",
													VVLyc9YCi: false,
													width: "100%",
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>
									)}
								</ResolveLinks>
								<ComponentViewportProvider height={44}>
									<SmartComponentScopedContainer
										className={"framer-19ivy49-container"}
										data-framer-name={"Rating"}
										layoutDependency={layoutDependency}
										layoutId={"d8VtNNHQp-container"}
										name={"Rating"}
										nodeId={"d8VtNNHQp"}
										rendersWithMotion={true}
										scopeId={"tnMZEkN8f"}
									>
										{_jsx4(stdin_default2, {
											height: "100%",
											id: "d8VtNNHQp",
											layoutId: "d8VtNNHQp",
											name: "Rating",
											width: "100%",
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
							</MotionDivWithFXWithOptimizedAppearEffect>
						</motion4.div>
						<ImageWithFXWithOptimizedAppearEffect
							__perspectiveFX={false}
							__smartComponentFX={true}
							__targetOpacity={1}
							animate={animation4}
							background={{
								alt: "",
								fit: "fit",
								pixelHeight: 6400,
								pixelWidth: 4266,
								positionX: "center",
								positionY: "center",
								sizes: `calc(${componentViewport?.width || "100vw"} - 50px)`,
								src: "https://framerusercontent.com/images/MCHQD7lDbeM6xNpgmpUbBFiURmg.png",
								srcSet:
									"https://framerusercontent.com/images/MCHQD7lDbeM6xNpgmpUbBFiURmg.png?scale-down-to=1024 682w,https://framerusercontent.com/images/MCHQD7lDbeM6xNpgmpUbBFiURmg.png?scale-down-to=2048 1365w,https://framerusercontent.com/images/MCHQD7lDbeM6xNpgmpUbBFiURmg.png?scale-down-to=4096 2730w,https://framerusercontent.com/images/MCHQD7lDbeM6xNpgmpUbBFiURmg.png 4266w",
							}}
							className={"framer-zcjbnp"}
							data-framer-appear-id={"zcjbnp"}
							data-framer-name={"Image"}
							initial={animation5}
							layoutDependency={layoutDependency}
							layoutId={"A3Pp8cNVE"}
							optimized={true}
							style={{
								borderBottomLeftRadius: 28,
								borderBottomRightRadius: 28,
								borderTopLeftRadius: 28,
								borderTopRightRadius: 28,
							}}
						/>
					</motion4.div>
				</Transition4>
			</Variants4>
		</LayoutGroup4>
	);
});
var css10 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-GGOxY.framer-z98i6t, .framer-GGOxY .framer-z98i6t { display: block; }",
	".framer-GGOxY.framer-2nahyi { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 66px; height: min-content; justify-content: center; max-width: 1200px; overflow: hidden; padding: 0px 25px 0px 25px; position: relative; width: 1200px; }",
	".framer-GGOxY .framer-14z3i77, .framer-GGOxY .framer-4fg36 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 18px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-GGOxY .framer-4q0li5-container, .framer-GGOxY .framer-1s4s09b-container, .framer-GGOxY .framer-19ivy49-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-GGOxY .framer-oey1vc { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-GGOxY .framer-132nqf1 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: wrap; gap: 10px; height: min-content; justify-content: center; max-width: 650px; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-GGOxY .framer-1cr8m3j, .framer-GGOxY .framer-9ahu6w, .framer-GGOxY .framer-zb8u71, .framer-GGOxY .framer-zh48yb, .framer-GGOxY .framer-yklocc, .framer-GGOxY .framer-19cjn1m { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-GGOxY .framer-456sa0 { flex: none; height: auto; max-width: 524px; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-GGOxY .framer-1acfzhu { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; overflow: hidden; padding: 10px 0px 0px 0px; position: relative; width: min-content; }",
	".framer-GGOxY .framer-zcjbnp { flex: none; gap: 10px; height: 675px; overflow: visible; position: relative; width: 100%; }",
	...css2,
	...css3,
	...css4,
];
var FramertnMZEkN8f = withCSS4(Component4, css10, "framer-GGOxY");
var stdin_default4 = FramertnMZEkN8f;
FramertnMZEkN8f.displayName = "HERO";
FramertnMZEkN8f.defaultProps = {
	height: 1171,
	width: 1200,
};
addFonts4(
	FramertnMZEkN8f,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...RatingTagFonts,
		...ButtonFonts,
		...UtilityRatingFonts,
		...getFontsFromSharedStyle4(fonts2),
		...getFontsFromSharedStyle4(fonts3),
		...getFontsFromSharedStyle4(fonts4),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framer.com/m/HEADER-fAug.js
var HEROFonts = getFonts2(stdin_default4);
var cycleOrder2 = ["WEzlX8iYB", "IS1NY8lPx", "ku4nx9cqe"];
var serializationHash5 = "framer-uFILp";
var variantClassNames5 = {
	IS1NY8lPx: "framer-v-1ka5q53",
	ku4nx9cqe: "framer-v-aupj1o",
	WEzlX8iYB: "framer-v-4d1wt2",
};
function addPropertyOverrides2(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition15 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition5 = ({ value, children }) => {
	const config = React5.useContext(MotionConfigContext5);
	const transition = value ?? config.transition;
	const contextValue = React5.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext5.Provider value={contextValue}>
			{children}
		</MotionConfigContext5.Provider>
	);
};
var Variants5 = motion5.create(React5.Fragment);
var humanReadableVariantMap2 = {
	Desktop: "WEzlX8iYB",
	Phone: "ku4nx9cqe",
	Tablet: "IS1NY8lPx",
};
var getProps5 = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap2[props.variant] ?? props.variant ?? "WEzlX8iYB",
	};
};
var createLayoutDependency5 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component5 = /* @__PURE__ */ React5.forwardRef(function (props, ref) {
	const fallbackRef = useRef5(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React5.useId();
	const { activeLocale, setLocale } = useLocaleInfo5();
	const componentViewport = useComponentViewport5();
	const {
		style,
		className: className7,
		layoutId,
		variant,
		...restProps
	} = getProps5(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState5({
		cycleOrder: cycleOrder2,
		defaultVariant: "WEzlX8iYB",
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames5,
	});
	const layoutDependency = createLayoutDependency5(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx5(serializationHash5, ...sharedStyleClassNames);
	return (
		<LayoutGroup5 id={layoutId ?? defaultLayoutId}>
			<Variants5 animate={variants} initial={false}>
				<Transition5 value={transition15}>
					<motion5.div
						{...restProps}
						{...gestureHandlers}
						className={cx5(
							scopingClassNames,
							"framer-4d1wt2",
							className7,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"WEzlX8iYB"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides2(
							{
								IS1NY8lPx: {
									"data-framer-name": "Tablet",
								},
								ku4nx9cqe: {
									"data-framer-name": "Phone",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<ComponentViewportProvider2
							height={1171}
							width={`max(${componentViewport?.width || "100vw"}, 1px)`}
							y={
								(componentViewport?.y || 0) +
								(130 + ((componentViewport?.height || 1325) - 154 - 1171) / 2)
							}
							{...addPropertyOverrides2(
								{
									ku4nx9cqe: {
										width: componentViewport?.width || "100vw",
										y:
											(componentViewport?.y || 0) +
											130 +
											(((componentViewport?.height || 1437) - 154 - 1171) / 2 +
												0 +
												0),
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<SmartComponentScopedContainer2
								className={"framer-1sj7z3r-container"}
								layoutDependency={layoutDependency}
								layoutId={"B4ZXKp1U6-container"}
								nodeId={"B4ZXKp1U6"}
								rendersWithMotion={true}
								scopeId={"ei9CC8o2_"}
							>
								{_jsx5(stdin_default4, {
									height: "100%",
									id: "B4ZXKp1U6",
									layoutId: "B4ZXKp1U6",
									style: {
										width: "100%",
									},
									width: "100%",
								})}
							</SmartComponentScopedContainer2>
						</ComponentViewportProvider2>
					</motion5.div>
				</Transition5>
			</Variants5>
		</LayoutGroup5>
	);
});
var css11 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-uFILp.framer-d2gu2o, .framer-uFILp .framer-d2gu2o { display: block; }",
	".framer-uFILp.framer-4d1wt2 { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 130px 0px 24px 0px; position: relative; width: 1200px; }",
	".framer-uFILp .framer-1sj7z3r-container { flex: 1 0 0px; height: auto; position: relative; width: 1px; }",
	".framer-uFILp.framer-v-1ka5q53.framer-4d1wt2 { width: 810px; }",
	".framer-uFILp.framer-v-aupj1o.framer-4d1wt2 { flex-direction: column; width: 390px; }",
	".framer-uFILp.framer-v-aupj1o .framer-1sj7z3r-container { flex: none; width: 100%; }",
];
var Framerei9CC8o2_ = withCSS5(Component5, css11, "framer-uFILp");
var stdin_default5 = Framerei9CC8o2_;
Framerei9CC8o2_.displayName = "HEADER";
Framerei9CC8o2_.defaultProps = {
	height: 1325,
	width: 1200,
};
addPropertyControls3(Framerei9CC8o2_, {
	variant: {
		options: ["WEzlX8iYB", "IS1NY8lPx", "ku4nx9cqe"],
		optionTitles: ["Desktop", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType3.Enum,
	},
});
addFonts5(
	Framerei9CC8o2_,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...HEROFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:header
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "ku4nx9cqe",
	md: "IS1NY8lPx",
	xl: "WEzlX8iYB",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"82783e7fcf4f326d8d9b4a72041dedf3d5360c1cd183094c631a3a227d30a683"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default5, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * Renders HeaderFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale, ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"82783e7fcf4f326d8d9b4a72041dedf3d5360c1cd183094c631a3a227d30a683"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default5}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default5);
var header_default = ComponentWithRoot;
export { header_default as default };
