// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 82783e7fcf4f326d "Nexora (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Tablet' | 'Phone' // Variant
}} Props

 */

/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */
import { routes } from "./chunks/chunk-4RDRNIVJ.js";

// virtual:hero
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framer.com/m/Hero-abc123.js
import { jsx as _jsx2, jsxs as _jsxs2 } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls as addPropertyControls2,
	ComponentViewportProvider,
	ControlType as ControlType2,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext,
} from "unframer";
import * as React from "react";
import { useRef as useRef2 } from "react";

// /:https://framerusercontent.com/modules/3fQArQTVkXC2tG6MAssm/RlhlmLRQlsWB2JTLJZfv/RqWlnUxLg.js
import { fontStore } from "unframer";
fontStore.loadFonts([
	"FS;Satoshi-medium",
	"FS;Satoshi-bold",
	"FS;Satoshi-bold italic",
	"FS;Satoshi-medium italic",
]);
var fonts = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "Satoshi",
				source: "fontshare",
				style: "normal",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/P2LQKHE6KA6ZP4AAGN72KDWMHH6ZH3TA/ZC32TK2P7FPS5GFTL46EU6KQJA24ZYDB/7AHDUZ4A7LFLVFUIFSARGIWCRQJHISQP.woff2",
				weight: "500",
			},
			{
				family: "Satoshi",
				source: "fontshare",
				style: "normal",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/LAFFD4SDUCDVQEXFPDC7C53EQ4ZELWQI/PXCT3G6LO6ICM5I3NTYENYPWJAECAWDD/GHM6WVH6MILNYOOCXHXB5GTSGNTMGXZR.woff2",
				weight: "700",
			},
			{
				family: "Satoshi",
				source: "fontshare",
				style: "italic",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/CDEBEFT2R7XKNGXSBBLZGMY4MMHZG75P/HEVKDGQCYDZ7Z6CDVR2ZQGBCTUD6ZARH/BKWEE3VKGTFABE37K2DTH625VUSN2N35.woff2",
				weight: "700",
			},
			{
				family: "Satoshi",
				source: "fontshare",
				style: "italic",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/NID3I7RITWZSKXRCJGOCMP5NOADJK6IG/2HLHGD7OBTWCOHW64YXOE5KFXHU4KJHM/ZHME2QIRFR7UPJ47NLY27RCAFY44CKZJ.woff2",
				weight: "500",
			},
		],
	},
];
var css = [
	`.framer-Hero .framer-styles-preset-hero-title:not(.rich-text-wrapper), .framer-Hero .framer-styles-preset-hero-title.rich-text-wrapper h1 { --framer-font-family: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-bold: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-bold-italic: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-italic: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 64px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 700; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 500; --framer-letter-spacing: -0.04em; --framer-line-height: 1.2em; --framer-paragraph-spacing: 20px; --framer-text-alignment: center; --framer-text-color: var(--token-38f68815-7867-4cb4-b7c3-02378b3e2eac, #0d0d0d); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }`,
	`.framer-Hero .framer-styles-preset-hero-subtitle:not(.rich-text-wrapper), .framer-Hero .framer-styles-preset-hero-subtitle.rich-text-wrapper p { --framer-font-family: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-bold: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-bold-italic: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-italic: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 20px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 500; --framer-letter-spacing: -0.02em; --framer-line-height: 1.5em; --framer-paragraph-spacing: 20px; --framer-text-alignment: center; --framer-text-color: var(--token-0e400885-4ad5-460c-800d-ba26ba3d28f7, #636363); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }`,
	`@media (max-width: 1199px) and (min-width: 810px) { .framer-Hero .framer-styles-preset-hero-title:not(.rich-text-wrapper), .framer-Hero .framer-styles-preset-hero-title.rich-text-wrapper h1 { --framer-font-size: 56px; } .framer-Hero .framer-styles-preset-hero-subtitle:not(.rich-text-wrapper), .framer-Hero .framer-styles-preset-hero-subtitle.rich-text-wrapper p { --framer-font-size: 18px; } }`,
	`@media (max-width: 809px) and (min-width: 0px) { .framer-Hero .framer-styles-preset-hero-title:not(.rich-text-wrapper), .framer-Hero .framer-styles-preset-hero-title.rich-text-wrapper h1 { --framer-font-size: 42px; } .framer-Hero .framer-styles-preset-hero-subtitle:not(.rich-text-wrapper), .framer-Hero .framer-styles-preset-hero-subtitle.rich-text-wrapper p { --framer-font-size: 17px; } }`,
];
var className = "framer-Hero";

// /:https://framer.com/m/Hero-abc123.js
var MotionSectionWithFX = withFX(motion2.section);
var cycleOrder = ["fjvIp9OuY", "MfLm91a81", "jbgy2BXo1"];
var serializationHash = "framer-Hero";
var variantClassNames = {
	fjvIp9OuY: "framer-v-1csbv5v",
	jbgy2BXo1: "framer-v-1ju41wd",
	MfLm91a81: "framer-v-1bnctof",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var animation = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 30,
};
var transition1 = {
	damping: 58,
	delay: 0.1,
	mass: 1,
	stiffness: 400,
	type: "spring",
};
var transition2 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion2.create(React.Fragment);
var humanReadableVariantMap = {
	Desktop: "fjvIp9OuY",
	Phone: "jbgy2BXo1",
	Tablet: "MfLm91a81",
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "fjvIp9OuY",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "fjvIp9OuY",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup2 id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition2}>
					<MotionSectionWithFX
						{...restProps}
						{...gestureHandlers}
						__framer__animate={{
							transition: transition1,
						}}
						__framer__animateOnce={true}
						__framer__enter={animation}
						__framer__styleAppearEffectEnabled={true}
						__framer__threshold={0.5}
						__perspectiveFX={false}
						__smartComponentFX={true}
						__targetOpacity={1}
						className={cx(
							scopingClassNames,
							"framer-1csbv5v",
							className2,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"fjvIp9OuY"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								jbgy2BXo1: {
									"data-framer-name": "Phone",
								},
								MfLm91a81: {
									"data-framer-name": "Tablet",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-hero-title"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"HeroTitle"}
							style={{
								"--extracted-r6o4lv":
									"var(--token-38f68815-7867-4cb4-b7c3-02378b3e2eac, rgb(13, 13, 13))",
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion2.h1
									className={"framer-styles-preset-hero-title"}
									data-styles-preset={"HeroTitle"}
									style={{
										"--framer-text-color":
											"var(--extracted-r6o4lv, var(--token-38f68815-7867-4cb4-b7c3-02378b3e2eac, rgb(13, 13, 13)))",
									}}
								>
									{"Transform Your Digital Vision Into Reality"}
								</motion2.h1>
							</React.Fragment>
						</RichText>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-hero-subtitle"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"HeroSubtitle"}
							style={{
								"--extracted-r6o4lv":
									"var(--token-0e400885-4ad5-460c-800d-ba26ba3d28f7, rgb(99, 99, 99))",
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion2.p
									className={"framer-styles-preset-hero-subtitle"}
									data-styles-preset={"HeroSubtitle"}
									style={{
										"--framer-text-color":
											"var(--extracted-r6o4lv, var(--token-0e400885-4ad5-460c-800d-ba26ba3d28f7, rgb(99, 99, 99)))",
									}}
								>
									{"We create exceptional digital experiences that drive growth and innovation for forward-thinking businesses."}
								</motion2.p>
							</React.Fragment>
						</RichText>
						<motion2.div
							className={"framer-hero-cta"}
							layoutDependency={layoutDependency}
							layoutId={"HeroCTA"}
							style={{
								alignItems: "center",
								display: "flex",
								flexDirection: "row",
								gap: "16px",
								justifyContent: "center",
							}}
						>
							<motion2.button
								className={"framer-hero-button-primary"}
								style={{
									backgroundColor: "var(--token-38f68815-7867-4cb4-b7c3-02378b3e2eac, #0d0d0d)",
									border: "none",
									borderRadius: "8px",
									color: "white",
									cursor: "pointer",
									fontFamily: "Satoshi, sans-serif",
									fontSize: "16px",
									fontWeight: "500",
									padding: "14px 28px",
									transition: "all 0.2s ease",
								}}
								whileHover={{
									scale: 1.05,
									backgroundColor: "#1a1a1a",
								}}
								whileTap={{
									scale: 0.95,
								}}
							>
								{"Get Started"}
							</motion2.button>
							<motion2.button
								className={"framer-hero-button-secondary"}
								style={{
									backgroundColor: "transparent",
									border: "1px solid var(--token-38f68815-7867-4cb4-b7c3-02378b3e2eac, #0d0d0d)",
									borderRadius: "8px",
									color: "var(--token-38f68815-7867-4cb4-b7c3-02378b3e2eac, #0d0d0d)",
									cursor: "pointer",
									fontFamily: "Satoshi, sans-serif",
									fontSize: "16px",
									fontWeight: "500",
									padding: "14px 28px",
									transition: "all 0.2s ease",
								}}
								whileHover={{
									scale: 1.05,
									backgroundColor: "var(--token-38f68815-7867-4cb4-b7c3-02378b3e2eac, #0d0d0d)",
									color: "white",
								}}
								whileTap={{
									scale: 0.95,
								}}
							>
								{"Learn More"}
							</motion2.button>
						</motion2.div>
					</MotionSectionWithFX>
				</Transition>
			</Variants>
		</LayoutGroup2>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-Hero.framer-uwmrpr, .framer-Hero .framer-uwmrpr { display: block; }",
	".framer-Hero.framer-1csbv5v { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 32px; height: min-content; justify-content: center; overflow: hidden; padding: 120px 0px 120px 0px; position: relative; width: 1200px; }",
	".framer-Hero .framer-hero-title { flex: none; height: auto; max-width: 800px; position: relative; white-space: pre-wrap; width: auto; }",
	".framer-Hero .framer-hero-subtitle { flex: none; height: auto; max-width: 600px; position: relative; white-space: pre-wrap; width: auto; }",
	".framer-Hero .framer-hero-cta { flex: none; height: auto; position: relative; width: auto; }",
	".framer-Hero.framer-v-1bnctof.framer-1csbv5v { padding: 100px 0px 100px 0px; width: 810px; }",
	".framer-Hero.framer-v-1ju41wd.framer-1csbv5v { gap: 24px; padding: 80px 20px 80px 20px; width: 390px; }",
	...css,
];
var FramerHeroComponent = withCSS(Component, css2, "framer-Hero");
var stdin_default = FramerHeroComponent;
FramerHeroComponent.displayName = "Hero";
FramerHeroComponent.defaultProps = {
	height: 600,
	width: 1200,
};
addPropertyControls2(FramerHeroComponent, {
	variant: {
		options: ["fjvIp9OuY", "MfLm91a81", "jbgy2BXo1"],
		optionTitles: ["Desktop", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType2.Enum,
	},
});
addFonts(
	FramerHeroComponent,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:hero
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "jbgy2BXo1",
	md: "MfLm91a81",
	xl: "fjvIp9OuY",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"82783e7fcf4f326d8d9b4a72041dedf3d5360c1cd183094c631a3a227d30a683"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * Renders HeroFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale, ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"82783e7fcf4f326d8d9b4a72041dedf3d5360c1cd183094c631a3a227d30a683"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var hero_default = ComponentWithRoot;
export { hero_default as default };
