// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 82783e7fcf4f326d "Nexora (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Tablet' | 'Phone' // Variant
}} Props

 */

/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */
import { routes } from "./chunks/chunk-4RDRNIVJ.js";

// virtual:partners
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framer.com/m/Partners-hmVe.js
import { jsx as _jsx2, jsxs as _jsxs2 } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls as addPropertyControls2,
	ComponentViewportProvider,
	ControlType as ControlType2,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	Image,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext,
} from "unframer";
import * as React from "react";
import { useRef as useRef2 } from "react";

// /:https://framerusercontent.com/modules/B2xAlJLcN0gOnt11mSPw/LHz3bw67SqHRmnCKTlE6/Ticker.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	Children,
	useEffect,
	useState,
	useRef,
	useMemo,
	useCallback,
	cloneElement,
	startTransition,
} from "react";
import { addPropertyControls, ControlType, RenderTarget } from "unframer";
import {
	useReducedMotion,
	LayoutGroup,
	useInView,
	useMotionValue,
	useTransform,
	motion,
	frame,
} from "unframer";
import { resize } from "@motionone/dom";
var MAX_DUPLICATED_ITEMS = 100;
var directionTransformers = {
	left: (offset) => `translateX(-${offset}px)`,
	right: (offset) => `translateX(${offset}px)`,
	top: (offset) => `translateY(-${offset}px)`,
	bottom: (offset) => `translateY(${offset}px)`,
};
function Ticker(props) {
	let {
		slots = [],
		gap,
		padding,
		paddingPerSide,
		paddingTop,
		paddingRight,
		paddingBottom,
		paddingLeft,
		speed,
		hoverFactor,
		direction,
		alignment,
		sizingOptions,
		fadeOptions,
		style,
	} = props;
	const { fadeContent, overflow, fadeWidth, fadeInset, fadeAlpha } =
		fadeOptions;
	const { widthType, heightType } = sizingOptions;
	const paddingValue = paddingPerSide
		? `${paddingTop}px ${paddingRight}px ${paddingBottom}px ${paddingLeft}px`
		: `${padding}px`;
	const currentTarget = RenderTarget.current();
	const isCanvas =
		currentTarget === RenderTarget.canvas ||
		currentTarget === RenderTarget.export;
	const filteredSlots = slots.filter(Boolean);
	const numChildren = Children.count(filteredSlots);
	const hasChildren = numChildren > 0;
	if (direction === true) {
		direction = "left";
	}
	const isHorizontal = direction === "left" || direction === "right";
	const offset = useMotionValue(0);
	const transformer = directionTransformers[direction];
	const transform = useTransform(offset, transformer);
	const parentRef = useRef(null);
	const childrenRef = useMemo(() => {
		return [
			{
				current: null,
			},
			{
				current: null,
			},
		];
	}, []);
	const [size, setSize] = useState({
		parent: null,
		children: null,
	});
	let clonedChildren = null;
	let dupedChildren = [];
	let duplicateBy = 0;
	let opacity = 0;
	if (isCanvas) {
		duplicateBy = numChildren ? Math.floor(10 / numChildren) : 0;
		opacity = 1;
	}
	if (!isCanvas && hasChildren && size.parent) {
		duplicateBy = Math.round((size.parent / size.children) * 2) + 1;
		duplicateBy = Math.min(duplicateBy, MAX_DUPLICATED_ITEMS);
		opacity = 1;
	}
	const measure = useCallback(() => {
		if (hasChildren && parentRef.current) {
			const parentLength = isHorizontal
				? parentRef.current.offsetWidth
				: parentRef.current.offsetHeight;
			const start = childrenRef[0].current
				? isHorizontal
					? childrenRef[0].current.offsetLeft
					: childrenRef[0].current.offsetTop
				: 0;
			const end = childrenRef[1].current
				? isHorizontal
					? childrenRef[1].current.offsetLeft +
						childrenRef[1].current.offsetWidth
					: childrenRef[1].current.offsetTop +
						childrenRef[1].current.offsetHeight
				: 0;
			const childrenLength = end - start + gap;
			startTransition(() =>
				setSize({
					parent: parentLength,
					children: childrenLength,
				}),
			);
		}
	}, []);
	const childrenStyles = isCanvas
		? {
				contentVisibility: "auto",
			}
		: {};
	if (hasChildren) {
		if (!isCanvas) {
			let initialResize = useRef(true);
			useEffect(() => {
				frame.read(measure);
				return resize(parentRef.current, ({ contentSize }) => {
					if (
						!initialResize.current &&
						(contentSize.width || contentSize.height)
					) {
						frame.read(measure);
					}
					initialResize.current = false;
				});
			}, []);
		}
		clonedChildren = Children.map(filteredSlots, (child, index) => {
			let ref;
			if (index === 0) {
				ref = childrenRef[0];
			}
			if (index === filteredSlots.length - 1) {
				ref = childrenRef[1];
			}
			const size2 = {
				width: widthType ? child.props?.width : "100%",
				height: heightType ? child.props?.height : "100%",
			};
			return (
				<LayoutGroup inherit={"id"}>
					<li ref={ref} style={size2}>
						{
							/* @__PURE__ */ cloneElement(
								child,
								{
									style: {
										...child.props?.style,
										...size2,
										flexShrink: 0,
										...childrenStyles,
									},
									layoutId: child.props.layoutId
										? child.props.layoutId + "-original-" + index
										: void 0,
								},
								child.props?.children,
							)
						}
					</li>
				</LayoutGroup>
			);
		});
	}
	const isInView = isCanvas ? true : useInView(parentRef);
	if (!isCanvas) {
		for (let i = 0; i < duplicateBy; i++) {
			dupedChildren = dupedChildren.concat(
				Children.map(filteredSlots, (child, childIndex) => {
					const size2 = {
						width: widthType ? child.props?.width : "100%",
						height: heightType ? child.props?.height : "100%",
						willChange: !isInView ? void 0 : "transform",
					};
					return (
						<LayoutGroup inherit={"id"}>
							<li style={size2} aria-hidden={true}>
								{
									/* @__PURE__ */ cloneElement(
										child,
										{
											key: i + " " + childIndex,
											style: {
												...child.props?.style,
												width: widthType ? child.props?.width : "100%",
												height: heightType ? child.props?.height : "100%",
												flexShrink: 0,
												...childrenStyles,
											},
											layoutId: child.props.layoutId
												? child.props.layoutId + "-dupe-" + i
												: void 0,
										},
										child.props?.children,
									)
								}
							</li>
						</LayoutGroup>
					);
				}),
			);
		}
	}
	const animateToValue =
		size.children + size.children * Math.round(size.parent / size.children);
	const initialTime = useRef(null);
	const prevTime = useRef(null);
	const xOrY = useRef(0);
	const isHover = useRef(false);
	const isReducedMotion = useReducedMotion();
	const listRef = useRef(null);
	const animationRef = useRef(null);
	if (!isCanvas) {
		useEffect(() => {
			if (isReducedMotion || !animateToValue || !speed) {
				return;
			}
			animationRef.current = listRef.current.animate(
				{
					transform: [transformer(0), transformer(animateToValue)],
				},
				{
					duration: (Math.abs(animateToValue) / speed) * 1e3,
					iterations: Infinity,
					easing: "linear",
				},
			);
			return () => animationRef.current.cancel();
		}, [hoverFactor, animateToValue, speed]);
		const playOrPause = useCallback(() => {
			if (!animationRef.current) return;
			const hidden = document.hidden;
			if (isInView && !hidden && animationRef.current.playState === "paused") {
				animationRef.current.play();
			} else if (
				(!isInView || hidden) &&
				animationRef.current.playState === "running"
			) {
				animationRef.current.pause();
			}
		}, [isInView]);
		useEffect(() => {
			playOrPause();
		}, [isInView]);
		useEffect(() => {
			document.addEventListener("visibilitychange", playOrPause);
			return () => {
				document.removeEventListener("visibilitychange", playOrPause);
			};
		}, [playOrPause]);
	}
	const fadeDirection = isHorizontal ? "to right" : "to bottom";
	const fadeWidthStart = fadeWidth / 2;
	const fadeWidthEnd = 100 - fadeWidth / 2;
	const fadeInsetStart = clamp(fadeInset, 0, fadeWidthStart);
	const fadeInsetEnd = 100 - fadeInset;
	const fadeMask = `linear-gradient(${fadeDirection}, rgba(0, 0, 0, ${fadeAlpha}) ${fadeInsetStart}%, rgba(0, 0, 0, 1) ${fadeWidthStart}%, rgba(0, 0, 0, 1) ${fadeWidthEnd}%, rgba(0, 0, 0, ${fadeAlpha}) ${fadeInsetEnd}%)`;
	if (!hasChildren) {
		return (
			<section style={placeholderStyles}>
				<div style={emojiStyles}>{"\u2728"}</div>
				<p style={titleStyles}>{"Connect to Content"}</p>
				<p style={subtitleStyles}>
					{"Add layers or components to infinitely loop on your page."}
				</p>
			</section>
		);
	}
	return (
		<section
			style={{
				...containerStyle,
				opacity,
				WebkitMaskImage: fadeContent ? fadeMask : void 0,
				maskImage: fadeContent ? fadeMask : void 0,
				overflow: overflow ? "visible" : "hidden",
				padding: paddingValue,
			}}
			ref={parentRef}
		>
			<motion.ul
				ref={listRef}
				style={{
					...containerStyle,
					gap,
					top:
						direction === "bottom" && isValidNumber(animateToValue)
							? -animateToValue
							: void 0,
					left:
						direction === "right" && isValidNumber(animateToValue)
							? -animateToValue
							: void 0,
					placeItems: alignment,
					position: "relative",
					flexDirection: isHorizontal ? "row" : "column",
					...style,
					willChange: isCanvas || !isInView ? "auto" : "transform",
					transform: transformer(0),
				}}
				onMouseEnter={() => {
					isHover.current = true;
					if (animationRef.current) {
						animationRef.current.playbackRate = hoverFactor;
					}
				}}
				onMouseLeave={() => {
					isHover.current = false;
					if (animationRef.current) {
						animationRef.current.playbackRate = 1;
					}
				}}
			>
				{clonedChildren}
				{dupedChildren}
			</motion.ul>
		</section>
	);
}
Ticker.defaultProps = {
	gap: 10,
	padding: 10,
	sizingOptions: {
		widthType: true,
		heightType: true,
	},
	fadeOptions: {
		fadeContent: true,
		overflow: false,
		fadeWidth: 25,
		fadeAlpha: 0,
		fadeInset: 0,
	},
	direction: true,
};
addPropertyControls(Ticker, {
	slots: {
		type: ControlType.Array,
		title: "Children",
		control: {
			type: ControlType.ComponentInstance,
		},
	},
	speed: {
		type: ControlType.Number,
		title: "Speed",
		min: 0,
		max: 1e3,
		defaultValue: 100,
		unit: "%",
		displayStepper: true,
		step: 5,
	},
	direction: {
		type: ControlType.Enum,
		title: "Direction",
		options: ["left", "right", "top", "bottom"],
		optionIcons: [
			"direction-left",
			"direction-right",
			"direction-up",
			"direction-down",
		],
		optionTitles: ["Left", "Right", "Top", "Bottom"],
		defaultValue: "left",
		displaySegmentedControl: true,
	},
	alignment: {
		type: ControlType.Enum,
		title: "Align",
		options: ["flex-start", "center", "flex-end"],
		optionIcons: {
			direction: {
				right: ["align-top", "align-middle", "align-bottom"],
				left: ["align-top", "align-middle", "align-bottom"],
				top: ["align-left", "align-center", "align-right"],
				bottom: ["align-left", "align-center", "align-right"],
			},
		},
		defaultValue: "center",
		displaySegmentedControl: true,
	},
	gap: {
		type: ControlType.Number,
		title: "Gap",
	},
	padding: {
		title: "Padding",
		type: ControlType.FusedNumber,
		toggleKey: "paddingPerSide",
		toggleTitles: ["Padding", "Padding per side"],
		valueKeys: ["paddingTop", "paddingRight", "paddingBottom", "paddingLeft"],
		valueLabels: ["T", "R", "B", "L"],
		min: 0,
	},
	sizingOptions: {
		type: ControlType.Object,
		title: "Sizing",
		controls: {
			widthType: {
				type: ControlType.Boolean,
				title: "Width",
				enabledTitle: "Auto",
				disabledTitle: "Stretch",
				defaultValue: true,
			},
			heightType: {
				type: ControlType.Boolean,
				title: "Height",
				enabledTitle: "Auto",
				disabledTitle: "Stretch",
				defaultValue: true,
			},
		},
	},
	fadeOptions: {
		type: ControlType.Object,
		title: "Clipping",
		controls: {
			fadeContent: {
				type: ControlType.Boolean,
				title: "Fade",
				defaultValue: true,
			},
			overflow: {
				type: ControlType.Boolean,
				title: "Overflow",
				enabledTitle: "Show",
				disabledTitle: "Hide",
				defaultValue: false,
				hidden(props) {
					return props.fadeContent === true;
				},
			},
			fadeWidth: {
				type: ControlType.Number,
				title: "Width",
				defaultValue: 25,
				min: 0,
				max: 100,
				unit: "%",
				hidden(props) {
					return props.fadeContent === false;
				},
			},
			fadeInset: {
				type: ControlType.Number,
				title: "Inset",
				defaultValue: 0,
				min: 0,
				max: 100,
				unit: "%",
				hidden(props) {
					return props.fadeContent === false;
				},
			},
			fadeAlpha: {
				type: ControlType.Number,
				title: "Opacity",
				defaultValue: 0,
				min: 0,
				max: 1,
				step: 0.05,
				hidden(props) {
					return props.fadeContent === false;
				},
			},
		},
	},
	hoverFactor: {
		type: ControlType.Number,
		title: "Hover",
		min: 0,
		max: 1,
		unit: "x",
		defaultValue: 1,
		step: 0.1,
		displayStepper: true,
		description: "Slows down the speed while you are hovering.",
	},
});
var containerStyle = {
	display: "flex",
	width: "100%",
	height: "100%",
	maxWidth: "100%",
	maxHeight: "100%",
	placeItems: "center",
	margin: 0,
	padding: 0,
	listStyleType: "none",
	textIndent: "none",
};
var placeholderStyles = {
	display: "flex",
	width: "100%",
	height: "100%",
	placeContent: "center",
	placeItems: "center",
	flexDirection: "column",
	color: "#96F",
	background: "rgba(136, 85, 255, 0.1)",
	fontSize: 11,
	overflow: "hidden",
	padding: "20px 20px 30px 20px",
};
var emojiStyles = {
	fontSize: 32,
	marginBottom: 10,
};
var titleStyles = {
	margin: 0,
	marginBottom: 10,
	fontWeight: 600,
	textAlign: "center",
};
var subtitleStyles = {
	margin: 0,
	opacity: 0.7,
	maxWidth: 150,
	lineHeight: 1.5,
	textAlign: "center",
};
var clamp = (num, min, max) => Math.min(Math.max(num, min), max);
var isValidNumber = (value) => typeof value === "number" && !isNaN(value);

// /:https://framerusercontent.com/modules/3fQArQTVkXC2tG6MAssm/RlhlmLRQlsWB2JTLJZfv/RqWlnUxLg.js
import { fontStore } from "unframer";
fontStore.loadFonts([
	"FS;Satoshi-medium",
	"FS;Satoshi-bold",
	"FS;Satoshi-bold italic",
	"FS;Satoshi-medium italic",
]);
var fonts = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "Satoshi",
				source: "fontshare",
				style: "normal",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/P2LQKHE6KA6ZP4AAGN72KDWMHH6ZH3TA/ZC32TK2P7FPS5GFTL46EU6KQJA24ZYDB/7AHDUZ4A7LFLVFUIFSARGIWCRQJHISQP.woff2",
				weight: "500",
			},
			{
				family: "Satoshi",
				source: "fontshare",
				style: "normal",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/LAFFD4SDUCDVQEXFPDC7C53EQ4ZELWQI/PXCT3G6LO6ICM5I3NTYENYPWJAECAWDD/GHM6WVH6MILNYOOCXHXB5GTSGNTMGXZR.woff2",
				weight: "700",
			},
			{
				family: "Satoshi",
				source: "fontshare",
				style: "italic",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/CDEBEFT2R7XKNGXSBBLZGMY4MMHZG75P/HEVKDGQCYDZ7Z6CDVR2ZQGBCTUD6ZARH/BKWEE3VKGTFABE37K2DTH625VUSN2N35.woff2",
				weight: "700",
			},
			{
				family: "Satoshi",
				source: "fontshare",
				style: "italic",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/NID3I7RITWZSKXRCJGOCMP5NOADJK6IG/2HLHGD7OBTWCOHW64YXOE5KFXHU4KJHM/ZHME2QIRFR7UPJ47NLY27RCAFY44CKZJ.woff2",
				weight: "500",
			},
		],
	},
];
var css = [
	`.framer-PLobl .framer-styles-preset-1ux6xyv:not(.rich-text-wrapper), .framer-PLobl .framer-styles-preset-1ux6xyv.rich-text-wrapper p { --framer-font-family: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-bold: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-bold-italic: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-italic: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 18px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 500; --framer-letter-spacing: -0.02em; --framer-line-height: 1.5em; --framer-paragraph-spacing: 20px; --framer-text-alignment: left; --framer-text-color: var(--token-0e400885-4ad5-460c-800d-ba26ba3d28f7, #636363); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }`,
	`@media (max-width: 1099px) and (min-width: 810px) { .framer-PLobl .framer-styles-preset-1ux6xyv:not(.rich-text-wrapper), .framer-PLobl .framer-styles-preset-1ux6xyv.rich-text-wrapper p { --framer-font-family: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-bold: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-bold-italic: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-italic: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 18px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: -0.02em; --framer-line-height: 1.5em; --framer-paragraph-spacing: 20px; --framer-text-alignment: left; --framer-text-color: var(--token-0e400885-4ad5-460c-800d-ba26ba3d28f7, #636363); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }`,
	`@media (max-width: 809px) and (min-width: 0px) { .framer-PLobl .framer-styles-preset-1ux6xyv:not(.rich-text-wrapper), .framer-PLobl .framer-styles-preset-1ux6xyv.rich-text-wrapper p { --framer-font-family: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-bold: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-bold-italic: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-family-italic: "Satoshi", "Satoshi Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 17px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: -0.02em; --framer-line-height: 1.5em; --framer-paragraph-spacing: 20px; --framer-text-alignment: left; --framer-text-color: var(--token-0e400885-4ad5-460c-800d-ba26ba3d28f7, #636363); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }`,
];
var className = "framer-PLobl";

// /:https://framer.com/m/Partners-hmVe.js
var TickerFonts = getFonts(Ticker);
var MotionSectionWithFX = withFX(motion2.section);
var cycleOrder = ["fjvIp9OuY", "MfLm91a81", "jbgy2BXo1"];
var serializationHash = "framer-D5Num";
var variantClassNames = {
	fjvIp9OuY: "framer-v-1csbv5v",
	jbgy2BXo1: "framer-v-1ju41wd",
	MfLm91a81: "framer-v-1bnctof",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var animation = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 18,
};
var transition1 = {
	damping: 58,
	delay: 0.1,
	mass: 1,
	stiffness: 400,
	type: "spring",
};
var transition2 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion2.create(React.Fragment);
var humanReadableVariantMap = {
	Desktop: "fjvIp9OuY",
	Phone: "jbgy2BXo1",
	Tablet: "MfLm91a81",
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "fjvIp9OuY",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "fjvIp9OuY",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup2 id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition2}>
					<MotionSectionWithFX
						{...restProps}
						{...gestureHandlers}
						__framer__animate={{
							transition: transition1,
						}}
						__framer__animateOnce={true}
						__framer__enter={animation}
						__framer__styleAppearEffectEnabled={true}
						__framer__threshold={0.5}
						__perspectiveFX={false}
						__smartComponentFX={true}
						__targetOpacity={1}
						className={cx(
							scopingClassNames,
							"framer-1csbv5v",
							className2,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"fjvIp9OuY"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								jbgy2BXo1: {
									"data-framer-name": "Phone",
								},
								MfLm91a81: {
									"data-framer-name": "Tablet",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-1ntlknw"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"UH2VulobD"}
							style={{
								"--extracted-r6o4lv":
									"var(--token-38f68815-7867-4cb4-b7c3-02378b3e2eac, rgb(13, 13, 13))",
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion2.p
									className={"framer-styles-preset-1ux6xyv"}
									data-styles-preset={"RqWlnUxLg"}
									style={{
										"--framer-text-alignment": "center",
										"--framer-text-color":
											"var(--extracted-r6o4lv, var(--token-38f68815-7867-4cb4-b7c3-02378b3e2eac, rgb(13, 13, 13)))",
									}}
								>
									{"Our collaborations include:"}
								</motion2.p>
							</React.Fragment>
						</RichText>
						<ComponentViewportProvider>
							<SmartComponentScopedContainer
								className={"framer-1f7hfuc-container"}
								data-framer-name={"Logos"}
								isAuthoredByUser={true}
								isModuleExternal={true}
								layoutDependency={layoutDependency}
								layoutId={"pkNGwbP3x-container"}
								name={"Logos"}
								nodeId={"pkNGwbP3x"}
								rendersWithMotion={true}
								scopeId={"ETlP2NduK"}
							>
								<Ticker
									alignment={"center"}
									direction={"left"}
									fadeOptions={{
										fadeAlpha: 0,
										fadeContent: true,
										fadeInset: 0,
										fadeWidth: 25,
										overflow: false,
									}}
									gap={52}
									height={"100%"}
									hoverFactor={1}
									id={"pkNGwbP3x"}
									layoutId={"pkNGwbP3x"}
									name={"Logos"}
									padding={10}
									paddingBottom={10}
									paddingLeft={10}
									paddingPerSide={false}
									paddingRight={10}
									paddingTop={10}
									sizingOptions={{
										heightType: true,
										widthType: true,
									}}
									slots={[
										<Image
											background={{
												alt: "",
												fit: "fit",
												pixelHeight: 35,
												pixelWidth: 132,
												positionX: "center",
												positionY: "center",
												src: "https://framerusercontent.com/images/4I0nUFgLGKqAqwEE0S5l6yrCXzQ.svg",
											}}
											className={"framer-10hsgg3"}
											data-framer-name={"Logo"}
											layoutDependency={layoutDependency}
											layoutId={"krvixNeWz"}
										/>,
										<Image
											background={{
												alt: "",
												fit: "fit",
												pixelHeight: 51,
												pixelWidth: 100,
												positionX: "center",
												positionY: "center",
												src: "https://framerusercontent.com/images/K7N7aNahky7BhBGyGdXp7oSDc.svg",
											}}
											className={"framer-1j7yc98"}
											data-framer-name={"Logo"}
											layoutDependency={layoutDependency}
											layoutId={"pQDZLNgdp"}
										/>,
										<Image
											background={{
												alt: "",
												fit: "fit",
												pixelHeight: 40,
												pixelWidth: 105,
												positionX: "center",
												positionY: "center",
												src: "https://framerusercontent.com/images/UsU6TSwGi1GYzawTJkBdu5BNeqg.svg",
											}}
											className={"framer-11nr756"}
											data-framer-name={"Logo"}
											layoutDependency={layoutDependency}
											layoutId={"q0IpOXuHX"}
										/>,
										<Image
											background={{
												alt: "",
												fit: "fit",
												pixelHeight: 30,
												pixelWidth: 140,
												positionX: "center",
												positionY: "center",
												src: "https://framerusercontent.com/images/Qifbcz2UjIveHTCuImUZcqT9kZg.svg",
											}}
											className={"framer-1vw113x"}
											data-framer-name={"Logo"}
											layoutDependency={layoutDependency}
											layoutId={"R9cQwNkzW"}
										/>,
										<Image
											background={{
												alt: "",
												fit: "fit",
												pixelHeight: 40,
												pixelWidth: 176,
												positionX: "center",
												positionY: "center",
												src: "https://framerusercontent.com/images/6QEz8kJbwqWFzbNDcgcMwaBk7Jk.svg",
											}}
											className={"framer-i01r6b"}
											data-framer-name={"Logo"}
											layoutDependency={layoutDependency}
											layoutId={"hWQdpQ5Qu"}
										/>,
										<Image
											background={{
												alt: "",
												fit: "fit",
												pixelHeight: 35,
												pixelWidth: 132,
												positionX: "center",
												positionY: "center",
												src: "https://framerusercontent.com/images/4I0nUFgLGKqAqwEE0S5l6yrCXzQ.svg",
											}}
											className={"framer-10hsgg3"}
											data-framer-name={"Logo"}
											layoutDependency={layoutDependency}
											layoutId={"krvixNeWz"}
										/>,
									]}
									speed={65}
									style={{
										height: "100%",
										maxWidth: "100%",
										width: "100%",
									}}
									width={"100%"}
								/>
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
					</MotionSectionWithFX>
				</Transition>
			</Variants>
		</LayoutGroup2>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-D5Num.framer-uwmrpr, .framer-D5Num .framer-uwmrpr { display: block; }",
	".framer-D5Num.framer-1csbv5v { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 36px; height: min-content; justify-content: center; overflow: hidden; padding: 48px 0px 48px 0px; position: relative; width: 1200px; }",
	".framer-D5Num .framer-1ntlknw { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-D5Num .framer-1f7hfuc-container { flex: none; height: 32px; max-width: 600px; position: relative; width: 100%; }",
	".framer-D5Num .framer-10hsgg3 { aspect-ratio: 3.7 / 1; height: var(--framer-aspect-ratio-supported, 30px); overflow: hidden; position: relative; width: 111px; }",
	".framer-D5Num .framer-1j7yc98, .framer-D5Num .framer-11nr756, .framer-D5Num .framer-i01r6b { aspect-ratio: 2.1666666666666665 / 1; height: var(--framer-aspect-ratio-supported, 30px); overflow: hidden; position: relative; width: 65px; }",
	".framer-D5Num .framer-1vw113x { aspect-ratio: 3.611111111111111 / 1; height: var(--framer-aspect-ratio-supported, 26px); overflow: hidden; position: relative; width: 94px; }",
	".framer-D5Num.framer-v-1bnctof.framer-1csbv5v { width: 810px; }",
	".framer-D5Num.framer-v-1ju41wd.framer-1csbv5v { padding: 38px 0px 38px 0px; width: 390px; }",
	...css,
];
var FramerETlP2NduK = withCSS(Component, css2, "framer-D5Num");
var stdin_default = FramerETlP2NduK;
FramerETlP2NduK.displayName = "Partners";
FramerETlP2NduK.defaultProps = {
	height: 191,
	width: 1200,
};
addPropertyControls2(FramerETlP2NduK, {
	variant: {
		options: ["fjvIp9OuY", "MfLm91a81", "jbgy2BXo1"],
		optionTitles: ["Desktop", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType2.Enum,
	},
});
addFonts(
	FramerETlP2NduK,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...TickerFonts,
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:partners
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "jbgy2BXo1",
	md: "MfLm91a81",
	xl: "fjvIp9OuY",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"82783e7fcf4f326d8d9b4a72041dedf3d5360c1cd183094c631a3a227d30a683"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * Renders PartnersFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale, ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"82783e7fcf4f326d8d9b4a72041dedf3d5360c1cd183094c631a3a227d30a683"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var partners_default = ComponentWithRoot;
export { partners_default as default };
